### ISSUE TITLE
About order management

### ISSUE THREAD

**Issue by CECchina** [allegro/allegro-api#2284]
Hello! I have some questions about the order management REST API:
Is there any API that can change the order into “Delivery”status?
Is there any API that can change the product's information? such as "good stock".
Is there any API that can cancel the order? If not, can we cancel the order on background management?

**Comment by MaciejFrackowiak** [comment]
I will answer to your questions:

1. not yet - we work on this functionality;
2. no, we don’t have it - but please describe what do you mean "good stock" for product information;
3. no, because in Allegro WWW service that option is not available too. You can cancel order in your internal system only.

**Comment by CECchina** [comment]
sorry, spelling mistakes.
"good stock" means "inventory of the goods"

**Comment by MaciejFrackowiak** [comment]
Thanks for reply. We have user own information for orders on suggestion list for REST API development.
