### ISSUE TITLE
Magetno 2 allegro moduł REST API

### ISSUE THREAD

**Issue by sportmma** [allegro/allegro-api#2814]
Czy w kategorii 124056 można powiązać ofertę z produktem? W module wyskakuje mi bład "Cannot create products in category: 124056" ?

**Comment by sportmma** [comment]
Mogę dostać odpowiedz w dwóch językach? Polski i Angielski Ponieważ mój wykonawca rozumie tylko w języku angielskim.

**Comment by sportmma** [comment]
Czy w dosłownie każdej kategorii można powiązać ofertę z produktem? Jeżeli tak co jest przyczyną błędu?

**Comment by sportmma** [comment]
POjawił się również problem produktów które nigdy wcześniej nie byly przesyłane. Występuje błąd "Product already exists. Please contact the application author." Wykonawca modułu uważa, że z ich strony wszystko działa
--

**Comment by sportmma** [comment]
Zeby powiązać ofertę z produktem każdy produkt w magento 2 musi mieć swój indywidualny ean czy wystarczy, że do konkretnej kategori przypisze tylko 1 ean?

**Comment by sportmma** [comment]
Gdy przesyłałem pordukty przez baselinker.com nie wymagał EAN. Chyba, ze baselinker sam automatycznie je nadaje?

**Comment by PatrykBocian** [comment]
Nie można powiązać oferty z  produktem w każdej kategorii. Możesz to sprawdzić za pomocą zasobu **GET /sale/categories/{categoryId}** - jeśli w odpowiedzi otrzymasz **"offersWithProductPublicationEnabled"=true**, w danej kategorii możesz powiązać ofertę z produktem. 

Zwróć uwagę, że wiązanie oferty z produktem, a tworzenie nowego produktu, to dwie inne funkcjonalności. Twój błąd jest odpowiedzią na próbę utworzenia produktu. To, czy w danej kategorii możesz dodać nowy produkt, znajdziesz w odpowiedzi dla **GET /sale/categories/{categoryId}** polu **“productCreationEnabled”**. W Twoim przypadku było to “**false**”, co oznacza, że w tej kategorii jest to niemożliwe.

 Produkt można dodać także tylko wtedy, kiedy jest to kategoria najniższego rzędu (pole **“leaf”:true**). Znajdziesz tu także informacje o konieczności dodania przynajmniej jednego kodu EAN - **"productEANRequired": true**.

Jeśli chodzi o błąd: “**Product already exists. Please contact the application author**” - tak jak wspomniałem w wątku [#2765](https://github.com/allegro/allegro-api/issues/2765):

Otrzymałeś taki komunikat, ponieważ próbowałeś utworzyć produkt, który już istnieje. Prześlij nam proszę pełen request tutaj (wtedy usuń wrażliwe dane, takie jak token) lub za pomocą [formularza kontaktowego](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). Tylko na podstawie tego jesteśmy w stanie stwierdzić, gdzie występuje błąd.

> “Zeby powiązać ofertę z produktem każdy produkt w magento 2 musi mieć swój indywidualny ean czy wystarczy, że do konkretnej kategori przypisze tylko 1 ean?”
> “Gdy przesyłałem pordukty przez baselinker.com nie wymagał EAN. Chyba, ze baselinker sam automatycznie je nadaje?”

Nie prowadzimy wsparcia dla Baselinker oraz Magento 2 - nie znamy ich działania. 

Tak jak wspomniałem wcześniej - wiązanie oferty  z produktem a tworzenie produktu, to dwa osobne procesy.  Możesz powiązać ofertę z produktem, który nie ma przypisanego EANu - informację o tym, czy taki posiada, sprawdzisz za pomocą  **GET /sale/products/{productId}** w tablicy “**eans**”. Natomiast to, czy przy tworzeniu nowego produktu, musisz dodać podać EAN, sprawdzisz przez **GET /sale/categories/{categoryId}** w polu  “**productEANRequired**”. Każdy produkt musi mieć swój indywidualny numer EAN. Więcej informacji na ten temat znajdziesz w naszym [poradniku](https://developer.allegro.pl/productization/). 

Poniżej wersja angielska dla Twojego wykonawcy.

You cannot assign offer to a product in each category. You can check this via **GET /sale/categories/{categoryId}**. If in the response you will receive "**offersWithProductPublicationEnabled"=true**, it means you can assign offer to a product. 

Please note that assigning offer to a product and proposing a new product are two different functionalities. Your error is the response to trying to create a new product. Whether you can add a new product in a given category, can be found in the response for **GET /sale/categories/{categoryId}** in the "**productCreationEnabled**" field.   In Your case it was “**false**”, which means it is impossible. 

Also, the product can be added in the lower level category (**“leaf”: “true”**). You will also find here information about at least one EAN code required - **"productEANRequired": true.** 

Regarding “**Product already exists. Please contact the application author**” - as I wrote before in [#2765](https://github.com/allegro/allegro-api/issues/2765) thread:

You received this error, because you tried to create a product that already exists. Please send us a full request here (then delete sensitive data, such as a token) or using the [contact form](https://allegro.pl/pomoc/kontakt?kategoria=a0f7ce34-c6f6-43e6-af7d-ad39bacce619&subjectId=517305f2-5ea1-4b3b-9080-d4cc960ab6a1). We need specific data to verify your case.

We do not provide support for Baselinker or Magento 2 - we do not knwo their software. 

As I mentioned before - assigning an offer to a product and creating a product are two different processes. You can assign an offer to a product that has no EAN - you can check it using  - values should be in the "**eans**" array. Use **GET /sale/categories/{categoryId}** (field “**productEANRequired**”) to check if the product in this category requires EAN. Each product must have its own individual EAN.

More information about assigning offers to a products, You will find in our [guide](https://developer.allegro.pl/en/productization/).
