### ISSUE TITLE
More than 50 characters title?

### ISSUE THREAD

**Issue by PC-Kerdezz** [allegro/allegro-api#4267]
Hello, 
In the API documentation, there is a 50 character limit for the offer title/product name. If I see the offer attached, there is much more than 50 characters on the left side up. How should our developer do that? Is that another field?

![Acqua di Gio 2021-03-12 131334](https://user-images.githubusercontent.com/80524624/110939841-5015a300-8336-11eb-9d04-563f79595f81.jpg)

Thank you for your help and sorry for a question, which is well known by developers.

**Comment by AureliuszBrussy** [comment]
Products in our Product Catalog may have names longer than 50 characters. The title of the offer can be up to 50 chars. 

When creating your offer (via [POST /sale/offers](https://developer.allegro.pl/en/documentation/#operation/createOfferUsingPOST)) you should make sure that its title does not exceed 50 characters. If you are using a product that already exists in our Product Catalog, make sure that its name is not longer than 50 characters, and if is - shorten it to the appropriate length.

If you use [POST /sale/product-offers](https://developer.allegro.pl/en/documentation/#operation/createProductOffers) to list an offer and you do not provide your own title - we will shorten the assigned product name accordingly, so that the offer can be listed.

**Comment by PC-Kerdezz** [comment]
Do you mean, that the 70-80-character long title in the left-upside corner is the title of the product in the Allegro Product Catalog?
Our problem is, that the 50 character is too short to give correct product names to the offers. There are variants and the customers do not read nor the product details, neither the category, but order based on the name of the products, "believing", that is is an Eau de Toilette (for example), instead of an after shave. Do you have any trick, how to be more precise to customers?

**Comment by AureliuszBrussy** [comment]
Yes, on your screenshot on the left-upside corner is the name of this product in the Allegro Product Catalog. On the offer page, we are showing the name of the product linked to this offer. The offer title is on the right side of the screenshot.  

You should assign the right product with the offer if the related product differs from the sold product. Check [our guide](https://developer.allegro.pl/en/productization/), where we explain how to assign offers to products.

**Comment by hahyes** [comment]
> Do you mean, that the 70-80-character long title in the left-upside corner is the title of the product in the Allegro Product Catalog?
> Our problem is, that the 50 character is too short to give correct product names to the offers. There are variants and the customers do not read nor the product details, neither the category, but order based on the name of the products, "believing", that is is an Eau de Toilette (for example), instead of an after shave. Do you have any trick, how to be more precise to customers?

You need to create offers based on product catalog. It slowly becomes requirement on Allegro, so I recommend update your application for creating "product offers". I'm doing the same thing lately. A lot of work, but what we can do? 
Cheers.
