### ISSUE TITLE
obtaining token information without manual action

### ISSUE THREAD

**Issue by ymyuceturk** [allegro/allegro-api#4531]
To get the token, I first run https://allegro.pl/auth/oauth/device, paste the **_"validation_uri_complete"_** value into the browser and continue.
Then with the **_"device_code"_** info
**_"https://allegro.pl/auth/oauth/token?grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Adevice_code&device_code=ZgN4O..."_**
I run it and I get my token. In this case, we have to manually trade to buy Tokens. How can we do this without manual action? I haven't been able to make any progress using the document.
I would like your directions.

Some transactions I made using the token;
product creation
product update
read the category list
reading orders
changing order statuses etc.

**Comment by AureliuszBrussy** [comment]
With first access_token you will receive refresh_token. In order to ensure that a user is not obliged to perform application authorization again, we make it possible to refresh tokens by refresh_token which is used to obtain a new access token for the user in a transparent way (without the need for the user to perform any actions). Refresh_token is valid for 3 months. You can read more about extending token validity in [our guide](https://developer.allegro.pl/en/auth/#extending-token-validity).

**Comment by ymyuceturk** [comment]
thanks for your reply
