### ISSUE TITLE
The bug for payment refund

### ISSUE THREAD

**Issue by shenli112** [allegro/allegro-api#4693]
Dear Allegro,

Our system has been connected to Allegro API, recently we meet one problem when refund payment to buyer by our system.

We encountered a system refund issue:

Every interface request to return a prompt fails, why can the refund succeed? And can refund multiple times successfully

For example，

Allegro order number：18db2850-d337-11eb-8681-b9af54feca53 
In fact, we only need to refund once, only 10pln, but now all payment has been refunded to buyer's account due to it's bug

![1](https://user-images.githubusercontent.com/83738462/125017362-904b1f00-e0a5-11eb-85d3-ad5276993073.png)

![payment refund](https://user-images.githubusercontent.com/83738462/125017835-7d851a00-e0a6-11eb-9568-9af0e0ef55ed.png)

could you please kindly inform us what the problem is? Thank you and look forward to hearing from you soon.

**Comment by MaciejFrackowiak** [comment]
I checked our logs and I see that you have already refunded all the money for the order=18db2850-d337-11eb-8681-b9af54feca53 - the last successful return was made on July 7th, 4:33 (Polish time zone). So now, you receive errors because you cannot return more money than you received in that order. You have to check your software settings or contact its author to explain why it still try to refund money if it's already done.
