### ISSUE TITLE
ConstraintViolationException.MissingRequiredParameters error on Creating Offer

### ISSUE THREAD

**Issue by aswiniimpro** [allegro/allegro-api#4761]
Got error when try to create offer using a product-id 6e49b585-5a16-4369-96a9-df4726391e55.
If we send manufacturer value in parameters we got error {"errors":[{"code":"ParameterCategoryException","message":"Unprocessable Entity","details":null,"path":"","userMessage":"Given parameter id 203433:Manufacturer should no have been passed as offer parameter."}]}

{
   "product":{
      "id":"6e49b585-5a16-4369-96a9-df4726391e55",
      "name":"XXX",
      "images":[
         "XXX"
      ]
   },
   "publication":{
      "status":"INACTIVE",
      "startingAt":null,
      "startedAt":null,
      "endingAt":null,
      "endedAt":null
   },
   "additionalServices":null,
   "external":{
      "id":"XXX"
   },
   "delivery":{
      "shippingRates":{
         "id":"XX"
      }
   },
   "parameters":[
      {
         "id":11323,
         "values":[
            
         ],
         "valuesIds":[
            "11323_1"
         ]
      }
   ],
   "category":{
      "id":"260341"
   },
   "name":"XXX",
   "payments":{
      "invoice":"VAT"
   },
   "sellingMode":{
      "format":"BUY_NOW",
      "price":{
         "amount":"22.67",
         "currency":"PLN"
      },
      "minimalPrice":{
         "amount":"22.67",
         "currency":"PLN"
      },
      "startingPrice":{
         "amount":"22.67",
         "currency":"PLN"
      }
   },
   "location":{
      "city":"XX",
      "countryCode":"XX",
      "postCode":"XX",
      "province":"XX"
   },
   "images":[
      "XX"
   ],
   "description":{
      "sections":[
         {
            "items":[
               {
                  "type":"TEXT",
                  "content":"XX"
               }
            ]
         }
      ]
   },
   "stock":{
      "available":10,
      "unit":"UNIT"
   }
}

Error Response :
[
   {
      "code":"ConstraintViolationException.MissingRequiredParameters",
      "message":"Complete the mandatory parameters: Manufacturer.",
      "details":"ConstraintViolationException.MissingRequiredParameters",
      "path":"parameters",
      "userMessage":"Complete the parameters mandatory: Manufacturer. "
   }
]

How to handle this exception error in API
Please help us to solve this issue.

**Comment by Lukasz-Zurek** [comment]
First of all, while using [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers), you are trying to provide parameter: 203433 in the **"parameters"** object, which is incorrect. You should provide this parameter in the **"product.parameters"** field (List of product parameters), because this parameter has: **"describesProduct": true**. You can check it via [GET /sale/categories/{categoryID}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2).
 
Please look at the second sample request in [our guide](https://developer.allegro.pl/en/product_offers/). You should provide parameter according to the following request:

```
...
{
"product":{
"id":"6e49b585-5a16-4369-96a9-df4726391e55",
"name":"XXX",
"parameters": [
    {
        "id": "203433",
        "valuesIds": [
        "203433_728620"
        ]
    }
    ],
"images":[
]
},
...
```
