### ISSUE TITLE
Cannot get data from endpoint /sale/product-offers/{offerId}/operations/{guid}

### ISSUE THREAD

**Issue by ahaw** [allegro/allegro-api#5409]
Występuje problem: 
 - [ X] z zasobem REST API / with a REST API resource
 - [X ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [X ] z logowaniem lub autoryzacją / with login or authorization

:beetle: **Opis / Description**

I get token using device flow which should give me access to resoure 
Then I'm trying to fetch operation info from endpoint: 
/sale/product-offers/{offerId}/operations/dabbe5c7-de06-4b44-87b7-ec661a0bbe5a

With header:
Accept :application/vnd.allegro.public.v1+json
Authorization:Bearer $token

The response is:
{
   "error": "unauthorized",
   "error_description": "Full authentication is required to access this resource"
}

As I see in documentation it require bearer-token-for-user which the same as /sale/offers/{offerId} endpoint which is working.

**Comment by PrzemyslawLukanowski** [comment]
Could you please send the trace-id connected with this error message? I've checked our logs and I can't confirm such error occurred - we returned the `303 See Other` response three times (02:12, 02:16, 02:49).

**Comment by ahaw** [comment]
A moment ago I tried another time to get fetch it and ive got error 401 
trace-id:9d61ae3805f9a0dc
guid: DABBE5C7-DE06-4B44-87B7-EC661A0BBE5A

**Comment by PrzemyslawLukanowski** [comment]
Thank you, to be clear - to the operation `/sale/product-offers/{id}/operations/dabbe5c7-de06-4b44-87b7-ec661a0bbe5a `we've returned another proper `303 See Other` response code (trace-id 662a0c18182e642b). The trace-id 9d61ae3805f9a0dc and `401 Unathorized` status is connected with request to the address from `Location` header from `/sale/product-offers/{id}/operations/dabbe5c7-de06-4b44-87b7-ec661a0bbe5a` - `GET /sale/product-offers/11788027**`*. And it seems that at this point the token is not being sent at all - we didn't logged any information about client-id and user-id during this attempt. Please make sure that you use a valid authorization not only at the first stage, when you're calling `GET /sale/product-offers/{id}/operations/dabbe5c7-de06-4b44-87b7-ec661a0bbe5a`, but also when there's a redirect to the address from `Location` header.

**Comment by ahaw** [comment]
I tried to perform again process of authenticating. 
And tried again with 
trace-id: ff5cd8ea3789e1a1
id: 11788027***
GUID: DABBE5C7-DE06-4B44-87B7-EC661A0BBE5A
and the same output.

I tried different endpoint this time /sale/offer-publication-commands/A8476A32-0E06-486C-9C21-7A04060E2983/tasks
which worked perfectly.
trace-id: 51f09461e816879

Both require same authentication type bearer-token-for-user
In both cases I add bearer Authorization header

**Comment by PrzemyslawLukanowski** [comment]
We've got here a similar situation like the one I wrote above. 

Timeline:
1. **time**: 11:59:59.180,
**trace-id**: 161011536e10862, 
**operation**: GET /sale/product-offers/11788027***/operations/DABBE5C7-DE06-4B44-87B7-EC661A0BBE5A
**result**: 303 See other
**comment**: Here you actually used a proper token, because we haven't returned the 401 code. In the Location header, we've returned the address with the offer data for which you're requesting in the next step.

2. **time**: 11:59:59.205,
**trace-id**: ff5cd8ea3789e1a1,
**operation**: GET /sale/product-offers/11788027***
**result**: 401 Unauthorized
**comment**: It seems that at this step, the token has been "lost", it's not being sent - the data in our logs don't contain any information about user or application context.

Please look at the schema below, are you sure you're using the proper token on the last stage? Looking at the second tile (GET /sale/product-offers/{offerID}/operations/{operationId}), I can assure you that the token is valid during this operation, but the problem occurs when moment after you're trying to request the data from the address received in the Location header (GET /sale/product-offers/{offerId}).

![async_api_publication_en](https://user-images.githubusercontent.com/51473661/152785216-e0e8b7ff-fe88-428d-81c2-d3eab14a5475.png)

**Comment by ahaw** [comment]
Ok, dziękę. Okazało się, że w c# HttpClient domyślnie czyści dane autoryzacyjne przy przekierowanie
