### ISSUE TITLE
Hello, thanks for your return.

### ISSUE THREAD

**Issue by clementmouret** [allegro/allegro-api#5474]
Hello, thanks for your return.

After clarification with our customer and his Allegro account manager, our customer is authorized to display the Allegro logo with a link to Allegro.pl customer shop product page (and not offers) and start to redirect high qualified traffic to Allegro. How can we use the API to get the product links and availability of our customer product catalog? We've created an app in the sandbox environment, but we can't figure out how to get product catalog, neither how to create a token as you don't have/need any shopper signin process (https://developer.allegro.pl/auth/#app).

Thank you for your help.
Best regards,
Swaven Team

_Originally posted by @clementmouret in https://github.com/allegro/allegro-api/issues/5319#issuecomment-1047871066_

**Comment by MaciejFrackowiak** [comment]
Our API is dedicated only to sellers, we do not have resources to allow customers to buy goods. It means that using API you cannot create a link to seller shop - you can do it only via the website. 
As a seller, you can only browse your offers via [GET /sale/offers](https://developer.allegro.pl/documentation/#operation/searchOffersUsingGET) - that resource requires bearer-token-for-user authorization (code or device flow) because the seller has to accept consent screen.
