### ISSUE TITLE
API implementation - Product / Offers Listing

### ISSUE THREAD

**Issue by mboes-nm** [allegro/allegro-api#5500]
Hey guys, we have a few question regarding the API implmentation:

1- For category's parameters (attributes) have 2 flags;

as mentioned in documentation

"requiredForProduct (whether you need to provide values for this parameter when you create a new product)

required (information whether parameter is required)"(Ref:https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2) 

does this mean if the parameter  has describesProduct = true then we take requiredForProduct only in consideration and ignore the required field ? and if it's describesProduct  = false we consider only the required flag ? 

2- Allegro has a way to create variant sets to create a link between variants, so Allegro create these variant sets automatically for some categories like fashion categories for example, the issue would be if I try to create a variant set on offers already existing in variant sets automatically created, can this cause an issue from Allegro's side, and if it is ,is there a way to disable this feature altogether and just create our own variants set in all cases. (ref : https://developer.allegro.pl/en/multi_variant_offers/)

3- In the following link (https://developer.allegro.pl/en/product_offers/#how-does-integration-with-an-asynchronous-api-work) it's said that after submitting the offer it's either processed immediately or we have to track it's processing through an operation  and once the operation is 'completed' it's said to check on the (/sale/product-offers/{offerId}) call , so my question is , is a 'completed' operation represent a successful offer integration, or does it only mean finished processing and that we need to check on the validation in the response of the product-offers/{offerId} call?

4- We tried creating variant sets (using this call https://developer.allegro.pl/documentation/#tag/Offer-variants[] )that vary according to color/pattern, and we got a successful response and checked that the variant set exists and it did, the issue is when we try viewing out offers from the "my offers" list in the sandbox, we don't see that the offer has a view where the user can choose the color (like we expected and saw on allegro website), does this mean there was an issue creating the set or is this due to us viewing the offer from our view or maybe because we're using the sandbox ?  I attached on the ticket how the product looks from our side although it's part of a variant set, other products of the set aren't visible next to this product. 
![image](https://user-images.githubusercontent.com/98888779/156348699-3257b31a-cb25-4180-8a48-6508fd5ede5c.png)

5- https://developer.allegro.pl/en/product_offers/#integration-with-an-asynchronous-api in this link it mentioned the following :Use the GET method on it to check the task status. In response, you will receive one of two statuses:"202 Accepted - the operation has not been completed yet. Repeat the previous request,303 See Other - the operation is finished. In the Location header, we will return a link to the new resource - /sale/product-offers/{offerId}. Use the GET method on it and in the response you will receive the current offer data." when I tried testing I got a status code = 200 and the offer returned in the response directly, and no information about the operation is returned. is this the expected behavior in the live environment and we would know if product is listed or not depending on the publication status ? I attached an example of the format I receive from the status call here (for call :https://api.allegro.pl.allegrosandbox.pl/sale/product-offers/7686419175/operations/885a6be2-647e-41e4-8a8d-a31038345cd0) [AllegroGetStatusResponse.json](https://jira.novomind.com/secure/attachment/373747/373747_AllegroGetStatusResponse.json)

6-According to this link ( [https://developer.allegro.pl/en/sale/#custom-parameters ](https://developer.allegro.pl/en/sale/#custom-parameter)) it says that some categories allow addition of custom attributes, and they're supposed to be transferred in an object separate from regular categories parameters, the thing is we use the calls mentioned in this link ( https://developer.allegro.pl/en/product_offers/ ) for submission of products, there's nothing mentioned in the documentation of these calls to explain how to handle custom attributes, so does this mean we can't send custom attributes in this case? and if we can how do we send them ?

Best Regards & many thanks in advance,
Matthias Bös

**Comment by MaciejFrackowiak** [comment]
Here are the answers:

1. A "requiredForProduct" flag means that you need to provide a value for this parameter when adding a new product proposal. An "options.describesProduct" flag says if that parameter is a product or offer parameter. Offer parameters are related to individual offer, e.g. condition, expiration date, but not with a specific product feature.
2. Yes, in some categories we create a multi-variant offers automatically. If you do not want to accept our multi-variant, you can delete it using [DELETE /sale/offer-variants/{setId}](https://developer.allegro.pl/documentation/#operation/deleteVariantSet). After that, we will not connect offers automatically again.
3. If you use [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers) and you will receive response with code 201 Created it means that offer is live. In other cases - with 202 Accepted you have to check its status with [GET /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getProductOffer).
4. Now, I see that variants are visible.
5. Please, give me a trace-id of your request. I will check it.
6. According to the tutorial, custom parameters are available only in /sale/offers model.

**Comment by fatemagnassar** [comment]
@MaciejFrackowiak Thanks a lot for the quick reply!
1-  The category parameter returns with two flags  **requiredForProduct** (which you already explain) and another separate field called required (this is the field I was referring to in my question),  I'm not sure what it represents ?
![image](https://user-images.githubusercontent.com/49574283/156987062-f243d1da-3337-4ec3-963d-c4379b8c9ed7.png)
2- so we can create a variant set for a product that already exists in another variant set created automatically by allegro without deleting the one created by allegro? and in this case would our product exist in 2 variant sets ? or would the set created by allegro be deleted automatically and replaced by our new set ?
3- _When I tried testing in the sandbox it went as follows_
- POST sale/product-offers/ with **trace-Id = "85bafe12cfd8fc36"** , I got a 202 status code 
 **_below are snippets of the responses and headers on postman_**
![image](https://user-images.githubusercontent.com/49574283/157033555-ed8c348c-771e-49a3-9e19-88606fa1caa6.png)
![image](https://user-images.githubusercontent.com/49574283/157033615-3d429d5b-b1e8-4770-831d-a62a4e87ac3a.png)

- As per discussion I took the location header link (in previous request) which was : https://api.allegro.pl.allegrosandbox.pl/sale/product-offers/7686936083/operations/8d4d8e00-3619-4131-b0fd-fcd3d153888e 
-Made the GET /sale/product-offers/{offerId}/operations/{operationId} request above with trace-Id = "430230ff5d0156ec" and I got 200 OK (which is not 202 or 303 as expected) , also I got the offer in the response and not the operation status as expected, so is this the behavior expected in live environment, because that goes against what's mentioned in the documentation   ?
 **_below are snippets of the responses and headers on postman_**
![image](https://user-images.githubusercontent.com/49574283/157033872-607a4925-cb06-457b-8f1f-451664aff280.png)
![image](https://user-images.githubusercontent.com/49574283/157033911-e33519dd-9dda-4bd4-b4a5-04656cb8c26d.png)

4- I think there's a misunderstanding concerning this point, What I meant is that this variant is part of a variant set I created (that varies on color/pattern) and that's how it looks from our view 
![image](https://user-images.githubusercontent.com/49574283/157034075-3312b3f7-d85b-49a0-a24d-4b088551ae0e.png)but this is what we expected it to look like **(not our product but an example from your website)**
![image](https://user-images.githubusercontent.com/49574283/157034115-e5e8354a-0bf5-4d58-9b44-942f009595f7.png)
my question is , does this mean the variant set wasn't created ? or is it just a matter of sandbox or a matter of who is viewing the product ?

Thanks alot and best regards!

**Comment by MaciejFrackowiak** [comment]
@fatemagnassar Next part of the answers:

1. Flag „required” refers to the offer parameter.
2. Yes, indeed, but there will be only one variant set because every single offer can exist in one set only.
3. I found your logs and now I am explaining that issue with the team. I will reply soon.
4. I will check it with the team responsible for functionality.

**Comment by MaciejFrackowiak** [comment]
@fatemagnassar Thanks for your patience, I am back with answers:
3. Postman, an application which you used for requests is responsible for that - it has an option "Automatically follow redirects", which follow HTTP 3xx responses as redirects. So you received 303 but in a second Postman redirected you to 200 OK;
4. There was some delay in multi-variant visibility - as I see now everything looks OK:
![obraz](https://user-images.githubusercontent.com/53566763/157666152-f82bf7d9-5abd-4787-9204-782a71630700.png)

**Comment by fatemagnassar** [comment]
Thanks alot, that was very helpful.
If it's okay I have a couple of other questions.

1- I noticed in your documentation you mentioned there might be limitations on the following calls https://developer.allegro.pl/documentation/#operation/createProductOffers and https://developer.allegro.pl/documentation/#operation/editProductOffers, May I know how many calls exactly are we allowed to make per time interval

2- We currently use https://developer.allegro.pl/documentation/#operation/createProductOffers this call to create products and offers in one request, and we update our data using https://developer.allegro.pl/documentation/#operation/editProductOffers call ,  I noticed that some fields aren't allowed to be updated like product category, already submitted product parameters, product name. I couldn't find any reference in the documentation to what we're allowed and not allowed to edit, so just wanted to check if there're further fields that we're not allowed to update or is that it ?

Thanks in advance and best regards.

**Comment by fatemagnassar** [comment]
Thanks alot !
Can you please confirm the following because we tested a lot of cases concerning the feedback and we're a bit confused..
1-when are the validation errors and warnings in this call https://developer.allegro.pl/documentation/#operation/getProductOffer return not equal to null ?
2-and do they affect the publication status of the product or the offer ?like could the product be listed but because it has validation errors not be sellable on your website ?
Best Regards.

**Comment by MaciejFrackowiak** [comment]
If you get an error on [GET /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getProductOffer), we will not publish an offer. Also, please clarify your question from point 1 or give us an example.

**Comment by fatemagnassar** [comment]
What I meant is the validation error object, all my attempts to send incorrect/ missing data always returns status code 422 when using the create or edit product offers calls, so when are validation errors/warning return with information, and if the product is accepted and has status listed, does the validation errors/warnings mean they're not sellable ?
![image](https://user-images.githubusercontent.com/49574283/158444463-02dc3e97-930b-4682-b3bd-7d7cea7a5a06.png)

**Comment by MaciejFrackowiak** [comment]
You can use [GET /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getProductOffer) to retrieve data for all of the offers from Allegro, also for those offers which were not created by [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers) resource. It means that as a result, you may receive some data in validation.error object for them. In most cases for [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers) or [PATCH /sale/product-offers/{offerId}](https://developer.allegro.pl/documentation/#operation/editProductOffers) you will get error 422.

Yes, "tax.percentage" field is deprecated - according to our [news](https://developer.allegro.pl/en/news/#vat-2021-preview) we will remove it in the future. We recommend using [GET /sale/tax-settings](https://developer.allegro.pl/documentation/#operation/getTaxSettingsForCategory) to receive tax settings for given category.

**Comment by fatemagnassar** [comment]
_Hello! I had a question concerning the listing of product-offers._
we currently have two accounts a seller account (we use to create product-offers) and a customer one (we use to buy offers and place orders)
We tried using out customer account to search the products we created on the sales account, we tried searching by the product name and offer name but we got no results, yet when we tried searching with the offerId we got our product in the results. Is this an issue with our data ? how do we get to find our product when we search by name ? what data do example of a product we tried searching for : https://allegro.pl.allegrosandbox.pl/oferta/test-product-4044903988283-7687363247

**Comment by MaciejFrackowiak** [comment]
I checked your offer and I could find it - I used a part of its name, e.g. "4044903988283" https://allegro.pl.allegrosandbox.pl/listing?string=4044903988283. You can browse offers by categories, parameters, name, etc. Also in API you can do it via [GET /offers/listings](https://developer.allegro.pl/documentation/#operation/getListing).

**Comment by fatemagnassar** [comment]
Thanks for the quick response !
I checked the link you sent and it's also the same thing, no results are shown, do you have an idea on what the problem is?
![image](https://user-images.githubusercontent.com/49574283/159924180-72a35ca4-4dcf-4e21-8462-d1193405b3cf.png)

**Comment by MaciejFrackowiak** [comment]
Please, switch to the Polish version of the Sandbox environment - it should help.
