### ISSUE TITLE
/sale/offer-publication-commands/ END offer request

### ISSUE THREAD

**Issue by yavuzresif** [allegro/allegro-api#5508]
/sale/offer-publication-commands/
We submitted an END offer request on 2022-02-22 and received a success response.  
We recently received an order for this product. Can you review this?

trace-id : c080bfd104506a86

**Comment by AureliuszBrussy** [comment]
Could you please send the offer id?

**Comment by yavuzresif** [comment]
offer id : 11425628862

**Comment by AureliuszBrussy** [comment]
The command associated with the trace-id: c080bfd104506a86 failed. Your software used the access_token of a user to whom the offer id 11425628862 does not belong.

**Comment by hahyes** [comment]
> We submitted an END offer request on 2022-02-22 and received a success response.

You need to check details of task after receiving success response, because /sale/offer-publication-commands/ is async resource. It means you're sending command which Allegro will execute. Success response doesn't mean offer is ended.

Use UUID of command to get details using this resource: https://developer.allegro.pl/redoc/redoc-static.html#operation/getPublicationTasksUsingGET

If status is NEW, command is still not done.
