### ISSUE TITLE
Ean issues when using POST createProductOffer call

### ISSUE THREAD

**Issue by fatemagnassar** [allegro/allegro-api#5604]
1-when testing the https://developer.allegro.pl/documentation/#operation/createProductOffers call on postman , I always get the following error no matter what ean i use, trace-id : '57c68e458a300971'
error response:
{
    "errors": [
        {
            "code": "ConstraintViolationException.ValidProduct",
            "message": "Podany EAN nie jest zgodny z jakimkolwiek EANem produktu.",
            "details": "ConstraintViolationException.ValidProduct",
            "path": "null",
            "userMessage": "Podany EAN nie jest zgodny z jakimkolwiek EANem produktu."
        }
    ]
}
2-another thing concerning the create product-offers call also, is when using a category-id :89508 , it has parameter EAN , as shown in the image below the required  flag is false , so from what I understand is that we don't have to send it when creating the product but for some reason when creating a product it returns the following error if we don't send the ean parameter'{
    "errors": [
        {
            "code": "ConstraintViolationException.ValidProduct",
            "message": "Brakuje parametru EAN (225693) o wartości: \"4049609166201\" dla oferty z produktem.",
            "details": "ConstraintViolationException.ValidProduct",
            "path": "null",
            "userMessage": "Brakuje parametru EAN (225693) o wartości: \"4049609166201\" dla oferty z produktem."
        }
    ]
}' trace-id = ''9f376aa556c97d6' 
![image](https://user-images.githubusercontent.com/49574283/162185367-bd49d87c-f8a3-4289-a6f2-90651fb7019c.png)

**Comment by hahyes** [comment]
BTW if you wanna have error responses in English, add this header

```
Accept-Language: en-US
```

**Comment by MaciejFrackowiak** [comment]
Here are the answers:
1. In our base we do not have any product with EAN code=4044903753416 (you can check it by [GET /sale/products?ean=4044903753416](https://developer.allegro.pl/documentation/#operation/getSaleProducts)). Then, we checked the parameters that you sent in a request - we recognized a product in our database with the same parameters - its id=5648256b-bdb5-4bc9-affe-7bf8e27d7cf6 ([GET /sale/products/{productId}](https://developer.allegro.pl/documentation/#operation/getSaleProduct)). However, that product has a different EAN code=4049609166201. We cannot create a new product, because we already have it - so you should use an EAN code 4049609166201, instead of 4044903753416.
2. It is not required to create a new product, but if a product has an EAN code in its product parameter structure, you have to use it - in this example, the product with id=5648256b-bdb5-4bc9-affe-7bf8e27d7cf6 has:
```
{
            "id": "225693",
            "name": "EAN",
            "valuesLabels": [
                "4049609166201"
            ],
            "values": [
                "4049609166201"
            ],
            "unit": null,
            "options": {
                "identifiesProduct": false,
                "isGTIN": true
            }
        }
```
So using it, you have to add a EAN code=4049609166201 to the request structure.

**Comment by fatemagnassar** [comment]
> BTW if you wanna have error responses in English, add this header
> 
> ```
> Accept-Language: en-US
> ```

Thanks alot for the helpful tip !

**Comment by Lukasz-Zurek** [comment]
@fatemagnassar 

> as for point number 2 because I'm kind of lost, So if the EAN parameter exist for a category, it means It's mandatory for this category but otherwise it's not ?

No. As my colleague has already mentioned - if a product has an EAN code in its product parameter structure, and you want to assign your offer to this product, you have to add a EAN code=4049609166201 (for example) to the request structure.
