### ISSUE TITLE
Can I use /sale/product-offers without approval from Allegro?

### ISSUE THREAD

**Issue by MartyQek** [allegro/allegro-api#5731]
Hi, before few weeks I get info that some decision team didn't approve me to use /sale/offers - I want to ask why? And I got new e-mail about /sale/product-offers - can I use them without the special approval or?

I need that functionality to work with products from my e-shop..
Thanks.

**Comment by PrzemyslawLukanowski** [comment]
Hi, nor /sale/offers or /sale/product-offers need any approval from us, but according to [yesterday's news](https://github.com/allegro/allegro-api/issues/5729) we recommend you to use /sale/product-offers, if you start integrating with us, because /sale/offers resources will be disabled in the future. 
The only resource that can be used only by verified applications is GET /offers/listing, so feel free to use all of the rest and don't hesitate to ask, if you face some problems during implementation.
