### ISSUE TITLE
Issue with Integrating Linker App

### ISSUE THREAD

**Issue by Mostwished** [allegro/allegro-api#5944]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Hi, 

We're currently having an issue with linking a third-party app to our Allegro account; the App in question is called Linker, which basically is an order management app. However, the team-members that are attempting to integrate this app have run into a problem; every time they try to actually download orders from Allegro, they get the following error: 

`GET [https://api.allegro.pl/sale/offers/12351883650`](https://api.allegro.pl/sale/offers/12351883650) resulted in a `403 Forbidden` response: {"errors":[{"code":"AccessDenied","message":"Access is denied","details":null,"path":null,"userMessage":"Access denied. (truncated...) ]

Do you know how we can fix this issue? Is it possible its an issue with permissions on our end, or something else that needs adjusting? 

Thanks!

Best Regards, 

Mostwished Team

**Comment by Lukasz-Zurek** [comment]
You receive 403 errors because your App is trying to retrieve detail information about the offer, using an authorization token which does not have a scope: **allegro:api:sale:offers:read** - which is needed to view detailed offer’s data, offer event journal & more. With the scopes you can define which functionalities your application will use. You will find the full list of our scopes right [here](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#list-of-available-scopes).

[On this site](https://apps.developer.allegro.pl/) - you can select and edit scopes for your application. But please note the fact that you should generate a new access token to have updated scopes. It won't work with your token validity extending process. If you use refresh tokens - only those scopes that were included in the refresh token will be available.

You will find more information about authorization using scope in [our guide](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#authorization-using-scope).

**Comment by Mostwished** [comment]
Hi Lukasz-Zurek,

Thanks for getting back to us so quickly!

I shall pass this information along to the relevant teams, and hopefully
they'll be able to get this working! In the meantime, I'd like to keep this
ticket open, just in case we do require any further assistance in this
regard.

Thanks!

Best Regards,

Mostwished Team (DG)
