### ISSUE TITLE
Access denied but have permissions

### ISSUE THREAD

**Issue by RuMont** [allegro/allegro-api#6072]
I am currently developing a marketplace and want to be able to publish my products in Allegro.

When trying to search for products I literally used the example request shown in the documentation, created a new access token just in case it was expired and checked if my permissions were set.

  curl -X GET \
  'https://api.allegro.pl/sale/products?phrase=888462600712&mode=GTIN' \
  -H 'Authorization: Bearer {token}' \
  -H 'Accept: application/vnd.allegro.public.v1+json'

![image](https://user-images.githubusercontent.com/73307917/187385673-626aa6b6-108f-47d1-95e6-d7a108eb001f.png)

The response I get is:

```
{
    "errors": [
        {
            "code": "AccessDeniedException",
            "message": "Access denied.",
            "details": null,
            "path": null,
            "userMessage": "Access denied."
        }
    ]
}
```

I got my access token using this url: https://allegro.pl/auth/oauth/token?grant_type=client_credentials

Thanks in advance.

**Comment by PrzemyslawLukanowski** [comment]
The problem is caused by the type of authorization you used - client_credentials. In our documentation you can find information on which type of authorization you should use to have access to a given endpoint:
- bearer-token-for-user: [authorization code](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#authorization-code-flow) or [device](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#device-flow) flow;
- bearer-token-for-application: [client credentials](https://developer.allegro.pl/tutorials/uwierzytelnianie-i-autoryzacja-zlq9e75GdIR#clientcredentials-flow);

**Comment by RuMont** [comment]
Is there any way to be able to see the products without prompting an user for their data? I am not dealing with logged users. I just need to check if a product already exists in the catalog so I publish mine or not.

**Comment by PrzemyslawLukanowski** [comment]
The interaction with the user is only required initially. After he/she performs authorization of the application you can use the [refresh token feature](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#extending-token-validity) to extend the token validity. There's no other way to skip this part in the bearer-token-for-user type of authorization.
