### ISSUE TITLE
Acccess Token Verification

### ISSUE THREAD

**Issue by IcoStan86** [allegro/allegro-api#6137]
Recentrly we've started using your platform. Our goal is to be able to have access to orders in our Allegro account via API.
The question I have is about obtaining access tokens. Now every access token has been manually verified by the user (our side). 
Is it possible to avoid manual token verification and complete verification only via API?

**Comment by MartaNowaczyk** [comment]
The basic access token (access_token) is valid for 12 hours. In order to ensure that a user is not obliged to perform application authorization twice a day, we also make it possible to refresh tokens by refresh_token which is used to obtain a new access token for the user in a transparent way (without the need for the user to perform any actions). Such a token is valid for 3 months and after first refresh, you can use it for another 60 seconds.
Thanks to so-called renewable token lifetime, each time you use the refresh token, you will receive a new pair - access token (valid for another 12 h) and refresh token (valid for another 3 months).
You can find more about authorization in our [tutorial](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY).

**Comment by IcoStan86** [comment]
Thank you for your reply. Yes I am familiar with the documentation.
So there is now way to avoid manual user token validation. In worse scenario every 3 months the user should create new token manually?

**Comment by MartaNowaczyk** [comment]
User doesn't need to login in the future to extend token validity. You can use [refresh token mechanism](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#extending-token-validity) without user actions.

**Comment by IcoStan86** [comment]
OK I got it. thank you very much.
