### ISSUE TITLE
Invalid authorization code

### ISSUE THREAD

**Issue by PrettyNail** [allegro/allegro-api#6236]
We try to access the order information from Allegro,but failed.
Firstly,we got the code from this website :https://allegro.pl/auth/oauth/authorize?response_type=code&client_id=80f4899a4e5a4a1ea79478a7706b15ee&redirect_uri=http://59.110.41.77/authCode.html
Then we try to use this code to get the token of store,it says this code is Invalid authorization code.

**Comment by MartaNowaczyk** [comment]
Error occurs because redirect_uri address which you put in your application is not the same as registered on our [website](https://apps.developer.allegro.pl/). Redirect_uri has to be the same as the one provided upon application registration. Remember that correct return address: 

- must be the URI address,
- must contain an HTTP(S) protocol,
- cannot contain URI fragments,
- cannot contain relative paths,
- cannot use IP addresses.
