### ISSUE TITLE
How to offers list from specific user

### ISSUE THREAD

**Issue by MGabala** [allegro/allegro-api#6281]
Is possible to get list of offers of specific user?

**Comment by PrzemyslawLukanowski** [comment]
It is possible via [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing), but [only verified applications](https://developer.allegro.pl/tutorials/how-to-search-and-browse-offers-XxWm2ykMYHl) have access to this resource.

**Comment by MGabala** [comment]
> 

Please tell me this is the Id:
https://allegro.pl/uzytkownik/**SmA_Kochmanski**

of an user?

**Comment by PrzemyslawLukanowski** [comment]
No, this is the user/seller login.

**Comment by MGabala** [comment]
> No, this is the user/seller login.

How i can get offers of this user? is this possible?

**Comment by PrzemyslawLukanowski** [comment]
Using GET /offers/listing?seller.login={sellerLogin} request. But as I wrote, you need your application to be verified to have access to this resource. More information can be found in [our guide](https://developer.allegro.pl/tutorials/how-to-search-and-browse-offers-XxWm2ykMYHl):

"**How to verify the application?**

If you are in the [Partnership Program](https://allegro.pl/dla-sprzedajacych/poznaj-nasz-program-partnerski-vip-O3ZORa6xPCm) for Sellers contact us via your account manager, otherwise contact us via the [form](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b)."

**Comment by MGabala** [comment]
Thanks for help!
