### ISSUE TITLE
Mapping with Channel Advisor 

### ISSUE THREAD

**Issue by justynamegamerchant** [allegro/allegro-api#6318]
[Allegro_Sleeve_Values.xlsx](https://github.com/allegro/allegro-api/files/9964081/Allegro_Sleeve_Values.xlsx)
![other brand](https://user-images.githubusercontent.com/117767299/200644923-bbb16ac8-925a-4452-a279-d0060424a3bf.png)
Hello, 
i work with Channel Advisor. I wanna sell my products on Allegro but i want my items will be uploaded on Allegro through Channel Advisor we have started mapping our items but we came accros the problem related to brand on Allegro. We have diffrent products with diffrent brands. Thats why we want to choose the value 'other' (inna in Polish) for that we got so many codes. I wii attach what we got. On the other hand we done it with long sleeve in our bathrobe. Again we got so much codes. We don't know which codes are correct. I kindly ask for help as Channel Advisor is not able to map our items because we got confused about the right value. Best regards, Justyna Różalska  
 [
[Allegro_Sleeve_Values.xlsx](https://github.com/allegro/allegro-api/files/9964054/Allegro_Sleeve_Values.xlsx)
![other brand](https://user-images.githubusercontent.com/117767299/200644354-fb5c8c35-fed5-44b8-af3e-7d07a8696d31.png)
](url)

**Comment by MaciejFrackowiak** [comment]
Every single value is correct because its value depends on category id - you can retrieve them by [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2). On GitHub we do not support Channel Advisor integration - if you have any doubts, you should contact Channel Advisor support directly.
