### ISSUE TITLE
Can't get attachment of message through API

### ISSUE THREAD

**Issue by jizhien** [allegro/allegro-api#6358]
[Występuje](url) problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production [environment]))
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

**Comment by jizhien** [comment]
Hi, I am trying to get the attachments in the customer message and reply message through the API, however, the request to get the attachments is rejected and indicates that we should contact the author of the application. For more details, please check the image below. And the thread ID for this example is 5DM6mLYeNsctUdSQ28fqIhdAA7N6jcscmbfEqqr1NW8. please check and help to fix this issue, thanks.
![request denied](https://user-images.githubusercontent.com/118327418/202076710-d598b47e-655f-410d-9e67-a5a23c17967a.png)
![request to get attachment](https://user-images.githubusercontent.com/118327418/202076732-20d29c6a-e1fd-46a9-bc7c-0e530104402b.png)

**Comment by MartaNowaczyk** [comment]
Check if your application has the scope "allegro: api: messaging" responsible for handling the message center. You can check it on the [Managing the Allegro applications](https://apps.developer.allegro.pl/) page. If you provide a list of scopes when generating a token, then the scope "allegro: api: messaging" should be included there too. If you do not provide such a list, it means that you have access in accordance with the selected scopes on the [Managing the Allegro applications](https://apps.developer.allegro.pl/) page. You can also decode your token and check if the correct scope is contained there. You must also use a bearer-token-for-user token. Please check your settings.
Otherwise, send the trace-id for verification.

**Comment by jizhien** [comment]
I double checked it and ensure that my application has the scope "allegro: api: messaging", but it still failed to get the attachment.
![application scopes](https://user-images.githubusercontent.com/118327418/202123232-6eaac20f-fcb4-4be9-aa30-a5a71dee4b99.png)

**Comment by MartaNowaczyk** [comment]
In the meantime, I was able to find your error calls in the logs. Download attachments using [GET /messaging/message-attachments/{attachmentId}](https://developer.allegro.pl/documentation/#operation/downloadAttachmentGET). Don't copy url from message thread such as "url": "https://edge.allegro.pl/message-center/message-attachments/xxx" because it's a wrong request.

**Comment by hahyes** [comment]
@MartaNowaczyk Czy coś mi umknęło jeżeli chodzi o ten zasób? Dostałem dzisiaj zgłoszenie, że nie działa pobieranie załączników. Sprawdzam w dokumentacji, a tam `api.` zamiast `upload.`. Nie jest to jakiś problem o wysokim priorytecie, ale z ciekawości - kiedy zaszła ta zmiana?

**Comment by MartaNowaczyk** [comment]
@hahyes jak tylko to sprawdzę dam Ci znać.

**Comment by MartaNowaczyk** [comment]
Ścieżka do pobierania załącznika się nie zmieniła i zawsze była z api. GET https://api.allegro.pl/messaging/message-attachments/{attachmentId}.
