### ISSUE TITLE
Several questions about API

### ISSUE THREAD

**Issue by MKI-Miro** [allegro/allegro-api#6854]
Hi

**1.** When I want to publish offer there are for example 2 products with same EAN. All these products have unique EAN. So I don't I understand why there are two often. This happens with many many products. Example of product: 5904438030354
**2.** When I want to publish offer I have to assign parameters even if product has them. Why? How do I know what parameters do I have to provide before I get error message. I am publishing 6000 offers for Puzzle category. Sometime offer is published without providing any parameter. Sometimes I have to provide. Wiek Dziecka or Kolekcja.
**3.** For several offers I have error message: 
"Usuń z opisu oferty adresy stron zewnętrznych, za pośrednictwem których prowadzona jest sprzedaż poza Allegro. Możesz podać adresy stron, na których umieszczone są jedynie informacje poszerzające wiedzę o oferowanym produkcie."
I am not providing any description. So why I am getting this error?
**4.** Sometime I have this error: 
Unprocessable Entity Parameter with ID `3475` not found in the specified category `259321`.
Dino 150 8590878393318 MICKEY 150 panoramic
3475 is Wiek Dziecka - so I dont understandy why I have this error message when it is puzzle for children
**5.** Sometime I get message:
"Unprocessable Entity The definitions of the parameter `3475:Wiek dziecka` were incorrectly specified as a parameter in section `offer`."

newOffer.Parameters.Add(
                            new AllegroApi.Domain.AllegroOffer.Parameter
                            {
                                Id = "3475",
                                Name = "Wiek dziecka",
                                ValuesIds = new List<string>
                                {
                                    "3475_70"
                                },
                                Values = new List<string>
                                {
                                    "8 lat +"
                                }
                            }
                        );
What do I have wrong?

**Comment by PrzemyslawLukanowski** [comment]
Hi,

1. Sometimes there may be more than one product because we identify products not only by EAN but also by their parameters. In this case, the second product is a duplicate, we should merge it with the original product in the meantime. If you receive an error message that indicates that there is more than one product for the given EAN, you should provide the product ID instead of GTIN in your payload.
2. That situation may happen if the product was created before we marked some of the parameters as required. Are you certain that the product has those parameters? Could you send us a sample trace-id?
3. It seems that this information must be included in the description or images of the product from our catalog. Could you send us the product IDs for which you have received this message?
4. The error message indicates that you are trying to provide parameter 3475, but the parameter with this ID doesn’t occur in the category in which you are trying to list offer - 259321. If you could send us a sample trace-id, we will verify it in detail.
5. It looks you specified this parameter in the „parameters” section instead of „productSet.product.parameters”. To specify which parameter is „offer” and which is „product”, please check the „options.describesProducts” flag in the response of [GET /sale/categories/{categoryID}/parameters](https://developer.allegro.pl/documentation#operation/getFlatParametersUsingGET_2).

**Comment by PrzemyslawLukanowski** [comment]
> Is it possible somehow report duplicate products?

Only using our [contact form](https://allegro.pl/pomoc/kontakt), we do not provide a such feature in the API.

**Comment by MKI-Miro** [comment]
5. Solved thank you

**Comment by MKI-Miro** [comment]
3:
For example: 
"e6c702f5-b4b9-49a6-a4e0-fcbf05d4fe7f"
"8478c42c-9e80-4aa4-b0a1-357795de6f75"

**Comment by PrzemyslawLukanowski** [comment]
Thank you. As I expected, the problem is connected to the data of the product, there's an address of the external website. I reported the problem with those two products to the team responsible for product data and I will let you know when the problem is solved. If you have more products with this issue, please send me their IDs. Sorry for the inconvenience.

**Comment by PrzemyslawLukanowski** [comment]
The problem with those two products is solved.
