### ISSUE TITLE
Deleted offers reappears

### ISSUE THREAD

**Issue by jakub-kanski** [allegro/allegro-api#6888]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Today we received email stating that offer 13480369146 was deleted ("Usunęliśmy twoją ofertę. Sprawdź jaka była tego przyczyna.") and it seems so after visiting its link (https://allegro.pl/oferta/oprogramowanie-windows-server-standard-2022-64bit-13480369146). However resource GET sale/offers still returns offer as "ENDED". Is there any way to distinguish deleted offer from ended one? Is it intended behaviour of this resource?

**Comment by Lukasz-Zurek** [comment]
It is intended behavior. The offer can be deleted by Allegro if it violates rules applicable on the website, especially the [Allegro Terms & Conditions](https://allegro.pl/terms). In that kind of situation the offer receives "ENDED" status and the Seller can list this offer again (as soon as he correct description/images which violated the rules).

In these resources:

- [GET /sale/offers/{offerId}](https://developer.allegro.pl/documentation/#operation/getOfferUsingGET),
- [GET /sale/offer-events](https://developer.allegro.pl/documentation/#operation/getOfferEvents),

we will return the value "ADMIN" in the "endedBy" field - which distinguishes deleted offer from ended one (ended by the user or according to the duration cycle). Please note the fact that this value refers to the offers ended due to violation of Allegro.pl rules and offers duplicated offers of the same item as well.
