### ISSUE TITLE
Verify application

### ISSUE THREAD

**Issue by Zabr69** [allegro/allegro-api#6913]
How can I verify the API application? When trying to execute a request I get the following error:

{'errors': [{'code': 'VerificationRequired', 'message': 'Access is denied. Verification is required.', 'details': None, 'path': None, 'userMessage': 'No access to the specified resource. Access is possible only for verified applications.'}]}

I have an account with 2 step verification active and I've already purchased a product in the past. client:59465765

**Comment by Lukasz-Zurek** [comment]
I understand that you mean [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) resource which is available only for verified apps. If you are in the [Partnership Program](https://allegro.pl/dla-sprzedajacych/poznaj-nasz-program-partnerski-vip-O3ZORa6xPCm) for Sellers contact us via your account manager, otherwise contact us via the [form](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).

**Comment by Zabr69** [comment]
> I understand that you mean [GET /offers/listing](https://developer.allegro.pl/documentation/#operation/getListing) resource which is available only for verified apps. If you are in the [Partnership Program](https://allegro.pl/dla-sprzedajacych/poznaj-nasz-program-partnerski-vip-O3ZORa6xPCm) for Sellers contact us via your account manager, otherwise contact us via the [form](https://allegro.pl/pomoc/kontakt?kategoria=4a6df9f8-0556-4b18-8930-68906a58c18e&subjectId=6093913a-efdf-4b94-a444-bde85b8c3d8b).

Thank you for the answer, I've taken the necessary steps described in your reply.
