### ISSUE TITLE
I can't synchronize Allegro (via API) with my site

### ISSUE THREAD

**Issue by Denys19871** [allegro/allegro-api#7274]
Good afternoon. I can't synchronize Allegro (via API) with my website, which I made using Shoplik builder. There is a synchronization module available in this constructor. Shoplik support service said that I need to contact Allegro support team. Here is the error number 72180b426eaaee73. Please help.

**Comment by MartaNowaczyk** [comment]
These types of codes is returned when redirect_uri is invalid. Make sure that the address you provided in redirect_uri is the same as the one you provided, when you registered the application. You can check and edit redirection addresses on page https://apps.developer.allegro.pl/.

**Comment by Denys19871** [comment]
Hi, I don't understand what I need to check. This is what it shows when I
click on the link
[image: image.png]
Please write down exactly what I need to do.

пн, 26 черв. 2023 р. о 07:08 MartaNowaczyk ***@***.***> пише:

**Comment by Denys19871** [comment]
Checked. Everything is correct.

**Comment by Denys19871** [comment]
But the synchronization still doesn't work

**Comment by MartaNowaczyk** [comment]
So redirect_uri is ok? What is the error/problem now? I am not familiar with the application, so contact its support and give me the details of the problem.

**Comment by Denys19871** [comment]
I just tried to synchronize and this is the error:

[image: image.png]

пн, 26 черв. 2023 р. о 15:08 MartaNowaczyk ***@***.***> пише:

**Comment by MartaNowaczyk** [comment]
I don't see this image, please send the full message you get there.

**Comment by Denys19871** [comment]
I don't understand what you mean.

пн, 26 черв. 2023 р. о 15:14 MartaNowaczyk ***@***.***> пише:

**Comment by MartaNowaczyk** [comment]
I don't see the graphic you sent in the previous message:

<img width="867" alt="Zrzut ekranu 2023-06-27 o 12 47 58" src="https://github.com/allegro/allegro-api/assets/38425363/405f069a-5f9f-4ba6-8963-8c53fada3995">

As I said before error occurs because redirect_uri address which is put in application is not the same as registered on our [website](https://apps.developer.allegro.pl/). Redirect_uri has to be the same as the one provided upon application registration. Provide such information to the developer or support of the software you are using (Shoplik support service).

**Comment by Denys19871** [comment]
Here's what the Shoplik support team last responded to me:

"Dzień dobry,
kod błędu służy do identyfikacji problemu, wiec nie rozumiem dlaczego
allegro miałoby nie przesłać Panu takiej informacji. Ten kod należy
przesłać do helpdesk allegro gdzie powinni wyjaśnić jaki jest problem u
Pana na koncie. To że  api allegro zwraca błąd może być spowodowane błędną
konfiguracją u Pana na koncie allegro, o czym już wielokrotnie informowałem
i na co nie mamy wpływu, (chociażby poprawność weryfikacji dwuetapowej).
Integracja działa poprawnie, konto było poprawnie skonfigurowane co pan
potwierdził. Proszę wyjaśnić z allego dlaczego integracja działała  a teraz
pojawia się ten ekran skoro twierdzi Pan  że nic nie zostało zmienione po
naszej konfiguracji."

They don't know what the cause of the error is


вт, 27 черв. 2023 р. о 13:07 MartaNowaczyk ***@***.***> пише:

**Comment by MartaNowaczyk** [comment]
We know what the code is in the first message, only in this one you sent a screenshot that doesn't display to me on this forum. The code you sent means that the redirect_uri being passed is incorrect. It is provided incorrectly https://mrjewelry.shoplik.pl/... , and the correct one (registered in the application) is https://mrjewelry.pl/.... - without shoplik. I have cut off the ends of the addresses because they are the same in both cases. Please forward this to shoplik support.

**Comment by Denys19871** [comment]
Good afternoon. These parameters are the same. This is specified in Allegro
API- https://mrjewelry.pl/admin/allegro/export/list and the same is
specified in the configuration settings on Shoplik
[image: image.png]

ср, 28 черв. 2023 р. о 06:44 MartaNowaczyk ***@***.***> пише:

**Comment by MartaNowaczyk** [comment]
The logs show otherwise. Please provide the new error code you are receiving. I'll check again to make sure you are sending the address correctly.

**Comment by MartaNowaczyk** [comment]
I have checked this error and the wrong redirect_uri is still provided. In the logs we have the information that all the time you give the wrong redirect_uri https://mrjewelry.shoplik.pl/admin/allegro/export/list instead of https://mrjewelry.pl/admin/allegro/export/list.
Let the application support check it carefully.

**Comment by Denys19871** [comment]
Good afternoon. The data is the same. But it still doesn't work.

чт, 29 черв. 2023 р. о 12:22 MartaNowaczyk ***@***.***> пише:

**Comment by MartaNowaczyk** [comment]
Please ask shoplik support to write to us on this topic in this thread or through the [contact form](https://allegro.pl/pomoc/kontakt). I would like to clarify this directly with them to solve the problem.

**Comment by Denys19871** [comment]
Shoplik's reply below

"Dzień dobry,
nie jesteśmy autoryzowani do zarządzania Pana kontem dlatego nie mamy
takiej możliwości, natomiast z tego co widzę Pana konto sklepu jest
połączone z jakimś kontem allegro, świadczy o tym to, że pobierane są
informacje, chociażby mapowanie kategorii. System nie wyrzuca do okna
autoryzacji allegro co świadczy że pobrany token jest aktywny i sklep jest
połączony z api allegro, w załączniku przesyłam filmik. Pytanie tylko jakie
konto zostało połączone ze sklepem? Proszę o to dopytać obsługę allegro."

ср, 5 лип. 2023 р. о 07:31 MartaNowaczyk ***@***.***> пише:

**Comment by MartaNowaczyk** [comment]
Categories can be downloaded without user authorization, hence this problem may not occur here. I understand that you corrected the redirect-uri and the authorization went through, only you have another problem with the account connection. Perhaps you were registered with another account when linking the application. On the account you want to be linked to you will check it in the [linked apps](https://allegro.pl/moje-allegro/moje-konto/powiazane-aplikacje). If it is not there, then you need to link again. Unfortunately, from my side, I don't see this information and I also don't know what target account you want to link.
