### ISSUE TITLE
Error listing offer with API-system EffectConnect

### ISSUE THREAD

**Issue by PlatformProducts** [allegro/allegro-api#7332]
Hi,

First of all, I would like to introduce myself: My name is Aleksander  and I work for Platform Products, a marketplace specialist operating in the audio industry based in The Netherlands. I have received your contact information from a platform we work with, called EffectConnect.

We are currently facing some issues regarding the listing of offers thru our API-system EffectConnect. All the products that we have selected to be listed on Allegro are getting an error, and we along with employees form EffectConnect do not know how to solve these errors because they are not informative.
![Error EffectConnect](https://github.com/allegro/allegro-api/assets/138680679/a3304a92-7e77-45f5-b235-136dcd74786f)

In the attachment I included a screenshot of the errors that I am currently recieving.

Kind regards,

Aleksander
![Error EffectConnect](https://github.com/allegro/allegro-api/assets/138680679/4e09284c-3a91-42a7-89a3-bbf2d2f6fb11)

**Comment by PrzemyslawLukanowski** [comment]
Hello Aleksander,

When it comes to the `"must not be blank"` I agree with you that the returned error is not very helpful so I ask the team responsible for this service to change it to more specific. More details can be found in the `path` field, which is `description.sections[0].items[0].content`. And by checking one of your requests I can see the following section:

```
	"description": {
		"sections": [{
			"items": [{
				"type": "TEXT",
				"content": ""
			}]
		}]
	},
```

So your application is sending the `"description"` field but is not providing anything in it. If you don't want to send `a "description"` and use the one from our Product Catalog, just remove this field from the payload.

I think the error `"at least one image should be attached to the product" `is self-described - you should include at least one image when you propose a new product.

`ParameterDoesNotExistExepction` is connected with the redundant parameter which is included in the payload. In this case, the returned parameter in the message is 204329. - it does not exist in the category 20078 in which you want to create a new product.

And the last `400 Bad Request` error code, it indicates that there was a problem with the syntax of your request, so we couldn't precisely return the specific reason. I've verified your request and it seems that the problem is with the lack of the "name" field - you didn't define it in the request.
