### ISSUE TITLE
503 Service Unavailable - /pricing/offer-fee-preview

### ISSUE THREAD

**Issue by BeeboLab** [allegro/allegro-api#7561]
Występuje problem: 
 - [X] z zasobem REST API / with a REST API resource
 - [X] ze środowiskiem produkcyjnym / with the production environment
 - [ ] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [X] inny / other

**503 - Service Unavailable while making a request for /pricing/offer-fee-preview**

While making multiple requests to retrieve fee calculations for given input data, from /pricing/offer-fee-preview endpoint, I'm constantly receiving 503 error. 
Tried couple dozen of requests within the span of 3 days, from 28.08.2023 to 30.08.2023, at different times of the day. 
Full dump of request/response data for the most recent request:

< POST /pricing/offer-fee-preview HTTP/1.1
< Host: api.allegro.pl
< User-Agent: python-requests/2.28.1
< Accept-Encoding: gzip, deflate, br
< Accept: application/vnd.allegro.public.v1+json
< Connection: keep-alive
< Authorization: Bearer [TOKEN]
< Content-Type: application/vnd.allegro.public.v1+json
< Content-Length: 377
< 
< {"offer": {"category": {"id": "147652"}, "parameters": [{"id": "11323", "name": "Stan", "values": ["Nowy"]}], "sellingMode": {"format": "BUY_NOW", "price": {"amount": "589.99", "currency": "PLN"}}, "publication": {"status": "NOT_REQUESTED"}, "promotion": {"emphasized": true, "bold": false, "highlight": false, "departmentPage": true, "emphasizedHighlightBoldPackage": false}}}

> HTTP/1.1 503 Service Unavailable
> expires: 0
> cache-control: no-cache, no-store, max-age=0, must-revalidate
> x-xss-protection: 1; mode=block
> pragma: no-cache
> x-frame-options: DENY
> trace-id: fbd5313da9d141ed
> date: Wed, 30 Aug 2023 20:03:19 GMT
> x-content-type-options: nosniff
> strict-transport-security: max-age=31536000 ; includeSubDomains
> content-type: application/json; charset=utf-8
> content-length: 190
> 
{"errors":[{"code":"SERVICE_UNAVAILABLE","message":"Service unavailable.","details":null,"path":null,"userMessage":"Server is unable to respond to your query. Try again in a few minutes."}]}

**Comment by MaciejFrackowiak** [comment]
The source of the issue was an authorization - [POST /pricing/offer-fee-preview](https://developer.allegro.pl/documentation/#operation/calculateFeePreviewUsingPOST) requires "bearer-token-for-user" authorization - you used a client_credentials authorization, which doesn't have a user context. Please, use [code](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#authorization-code-flow) or [device](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#device-flow) flow to receive a correct results. Of course, I reported an incorrect behaviour of the resource - you shouldn't receive error 503.

**Comment by BeeboLab** [comment]
This worked perfectly, thank you for your help!
