### ISSUE TITLE
How to Retrieve and Modify Published Product Information?

### ISSUE THREAD

**Issue by yangsheng8** [allegro/allegro-api#7615]
Hello, our company needs to retrieve and modify products. May I ask where can I find the APIs for that?
I've tried the following but failed:
### 1. Retrieve information (including name, price, stock) of all active product listings under an account:
I used this API but couldn't get them:
```
GET /sale/offers?publication.status=ACTIVE

response:
{
    "offers": [],
    "count": 0,
    "totalCount": 0
}
```

### 2. Modify price and stock for a product. I tried the following API but got an error. What did I do wrong?
```
PATCH /sale/product-offers/{offerId}

request:
Params: 
offerId: 14130126970
Headers:  
Accept : application/vnd.allegro.public.v1+json
Authorization : Bearer  xxxxxx
   
Body:
{
  "sellingMode": {
    "format": "BUY_NOW",
    "price": {
      "amount": "9999.12",
      "currency": "PLN"
    }
  }  
}
```
```
response:
{
  "errors": [
    {
      "code": "NotAllowedException",
      "message": "The HTTP method is not allowed",
      "details": null,
      "path": null,
      "userMessage": "An error occurred"
    }
  ]
}
```
Could you please help me understand what went wrong and how to successfully obtain and modify product prices and inventory?
Thank you for your help. I look forward to your prompt reply.
Best regards

**Comment by PrzemyslawLukanowski** [comment]
Could you please send me a sample trace ID of your attempt to modify the offer? I've searched our logs, but couldn't find any trace of using the PATCH method or /sale/product-offers/{offerId} for the seller, who is the owner of this offer.

**Comment by PrzemyslawLukanowski** [comment]
And when it comes to the issue of retrieving product information, it seems that you are not authorized as a seller who has any offers. Also, in this case, I will need a trace ID to verify it in detail.

**Comment by yangsheng8** [comment]
> And when it comes to the issue of retrieving product information, it seems that you are not authorized as a seller who has any offers. Also, in this case, I will need a trace ID to verify it in detail.

Is the trace ID the same as the product ID? 
Here is the information corresponding to the product: 
VidaXL Szafka, 118 x 30 x 75 cm, lite drewno mango
ID: 14130126970
reference number: SKU191859-da234b43-42a3-422c-8054-a826f7f8edad
EAN (GTIN): 6900472467018 

Additionally, I have registered an application and obtained a token. Isn't the bearer token for the user supposed to grant access to all APIs?

**Comment by PrzemyslawLukanowski** [comment]
> Is the trace ID the same as the product ID?

No, the trace ID is connected with the specific request from your application, and [product](https://developer.allegro.pl/tutorials/glossary-LRVjol8kdCA#product) or [offer](https://developer.allegro.pl/tutorials/glossary-LRVjol8kdCA#offer) IDs are associated with entities on Allegro. Trace ID can be retrieved from the headers in the response. I don't see any attempts in our logs to modify offer 14130126970 or any other offer in the last 7 days from the "Si****" account, that's why I need the trace ID to verify the issue.  You can also decode your token using [this site](https://jwt.io/) and check whether the value in "user_name" is proper (it should be ******063)

> Additionally, I have registered an application and obtained a token. Isn't the bearer token for the user supposed to grant access to all APIs?

It depends on which flow you use. [Code](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#authorization-code-flow) and [device](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#device-flow) flow give you access to ro resources marked as bearer-token-for-user in our documentation, and [client_credentials](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#clientcredentials-flow) gives you access to those with bearer-token-for-application annotation:

<img width="634" alt="Zrzut ekranu 2023-09-13 o 14 09 00" src="https://github.com/allegro/allegro-api/assets/51473661/3f96aae7-bff0-49db-8b2d-948caacdf091">

**Comment by yangsheng8** [comment]
> > Is the trace ID the same as the product ID?
> 
> No, the trace ID is connected with the specific request from your application, and [product](https://developer.allegro.pl/tutorials/glossary-LRVjol8kdCA#product) or [offer](https://developer.allegro.pl/tutorials/glossary-LRVjol8kdCA#offer) IDs are associated with entities on Allegro. Trace ID can be retrieved from the headers in the response. I don't see any attempts in our logs to modify offer 14130126970 or any other offer in the last 7 days from the "Si****" account, that's why I need the trace ID to verify the issue. You can also decode your token using [this site](https://jwt.io/) and check whether the value in "user_name" is proper (it should be ******063)
> 

Retrieve product
GET https://api.allegro.pl/sale/offers
```
trace-id	5197cfe02d95c150
```

Modify price
PATCH https://api.allegro.pl/sale/product-offers
```
trace-id	da2db83fa102fea8
```

**Comment by PrzemyslawLukanowski** [comment]
> Retrieve product
> GET https://api.allegro.pl/sale/offers
> 
> trace-id	5197cfe02d95c150
>

The response is correct because you are authorized as a different user - ***040, who does not have any ACTIVE offers and who is not an owner of the offer mentioned above.

> Modify price
> PATCH https://api.allegro.pl/sale/product-offers
> 
> trace-id	da2db83fa102fea8
> 
You are using /sale/product-offers path and providing offer ID as a query parameter - /sale/product-offers?offerId=14130126970. The correct way is to put offerID directly in the path, like this - /sale/product-offers/14130126970

**Comment by yangsheng8** [comment]
> > Retrieve product
> > GET https://api.allegro.pl/sale/offers
> > trace-id	5197cfe02d95c150
> 
> The response is correct because you are authorized as a different user - ***040, who does not have any ACTIVE offers and who is not an owner of the offer mentioned above.
> 
> > Modify price
> > PATCH https://api.allegro.pl/sale/product-offers
> > trace-id	da2db83fa102fea8
> 
> You are using /sale/product-offers path and providing offer ID as a query parameter - /sale/product-offers?offerId=14130126970. The correct way is to put offerID directly in the path, like this - /sale/product-offers/14130126970

Hello, I changed to use an account with higher privileges. And, I selected all the permissions when creating the app. 
### 1. Why are all the products I retrieved showing "status": "ENDED"? 
`GET https://api.allegro.pl/sale/offers`
trace-id   4768ddccd9ab8627
Am I using the wrong API? How can I get active products? 
### 2. I can modify product price and stock in the backend, but unable to do so via API.
`PATCH https://api.allegro.pl/sale/product-offers/14218293950`
trace-id   f9ca1e12d0988353
The error response is:
```{
    "errors": [
        {
            "code": "OfferAccessDeniedException",
            "message": "Forbidden",
            "details": null,
            "path": "",
            "userMessage": "Access denied. You are not authorized to perform operations on the indicated offer"
        }
    ]
}```
If I need to modify price and stock via API, what parameters should I specify?

**Comment by PrzemyslawLukanowski** [comment]
1. I see that your offers were ended by the user, using browser form or flat files. You can activate offer with PATCH method, [here's](https://developer.allegro.pl/tutorials/how-to-process-list-of-offers-m09BKA5v8H3#offer-status-change) an example, or using [PUT /sale/offer-publication-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/changePublicationStatusUsingPUT).
2. In this example, you tried to modify the offer which belongs to seller ******489, while being authorized as a seller *****2040. That's why we returned 403 Forbidden status.

**Comment by yangsheng8** [comment]
> 1. I see that your offers were ended by the user, using browser form or flat files. You can activate offer with PATCH method, [here's](https://developer.allegro.pl/tutorials/how-to-process-list-of-offers-m09BKA5v8H3#offer-status-change) an example, or using [PUT /sale/offer-publication-commands/{commandId}](https://developer.allegro.pl/documentation/#operation/changePublicationStatusUsingPUT).
> 2. In this example, you tried to modify the offer which belongs to seller ******489, while being authorized as a seller *****2040. That's why we returned 403 Forbidden status.

You mentioned seller ******489 and seller *****2040. Where can I find the seller ID?

**Comment by PrzemyslawLukanowski** [comment]
You can find it in the response to [GET /me](https://developer.allegro.pl/documentation#operation/meGET).

**Comment by yangsheng8** [comment]
> You can find it in the response to [GET /me](https://developer.allegro.pl/documentation#operation/meGET).

I'm a little confused. Why does the API call resources of seller *****2040 when I use the application created by seller ******489?

**Comment by PrzemyslawLukanowski** [comment]
It doesn't matter who created the application, but who authorized it to perform the operations on his behalf. One application can be used by many different sellers. We describe user authorization step [here in our tutorial.](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#user-authorization)

**Comment by PrzemyslawLukanowski** [comment]
It depends on which user you were logged in when you authorized the application. If on a different account than the "zonbai" - it doesn't matter who is the owner of the client ID and client secret, but who authorized the application. The token will be associated with this user.
