### ISSUE TITLE
Print labels in bulk

### ISSUE THREAD

**Issue by t0is** [allegro/allegro-api#7631]
Hello. 

Is there a way to print multiple labels at once? 

According to the documentation, it is only possible for one parcel at a time. 

This is a bit weird and unsual. The inconvenience, we can work with that. 

But the main issue is - it always prints on the first 1/4 of the page (when printing to A4 format). 
This basically means that we are able to print one label, turn the page around, print another one. 

And since the API also does not support offset for the labels, there will always be two labels I am not able to print at  
```
.................. |....................
PRINTED............|........NOT....
...................|....................
...................|....................
---------------------------------------
...................|....................
..NOT..............|...PRINTED
...................|....................
...................|....................
```
                    
NOT represents the area that is NOT ACCESSIBLE at all with this logic.

Is there something I am missing? This creates a lot of waste and a lot of extra costs.

Thanks a lot for suggestions.

**Comment by Lukasz-Zurek** [comment]
@t0is I will consult it with another department as soon as possible and will come back with an answer for you. Please be patient.

**Comment by t0is** [comment]
@Lukasz-Zurek Thank you, please let me know. 

I would like to point out that the key date is 25th October.

This is the date when allegro releases the changes for Allegro SMART, adding Allegro One as a requirement. Therefore we need at least a few days prior to finalize the implementation.

Since these packages are required to be sent via Allegro, we need API so we do not have to do it manualy. 

Without the API, we are not able to fulfill those requirements effectively. 

Thank you, 
t0is

**Comment by Lukasz-Zurek** [comment]
@t0is Unfortunately our API allows you only to download label(s) for only 1 order, apart from the order for a DPD multi-pack, where after selecting the A4 format, we will have many labels on one page. However, for the rest of the carriers in this case it will always be 1 label.

In the case of A4 label format, the label is located on 1/4 of the page and in the case of A6 it takes up the entire page.

**Comment by t0is** [comment]
@Lukasz-Zurek I know that, can you ask the team to make a change? 

I understand it is not an issue for someone sending 1 package a day, but for bigger sellers, it is a bit of a problem. 
Not only that, but it is not ECO friendly at all, the amount of waste is unnecessarry, we pretty much throw away half of our money paper and money we put into the labels. 

When doing it manualy, you can print multiple labels at the same time, on the same page, therefore it is surely not that hard to implement also for the API call.

**Comment by Lukasz-Zurek** [comment]
I fully understand this need, but it is difficult for us because we cooperate with a logistics operator. We are therefore not fully responsible for this way of managing labels. Please send us a suggestion in [Discussions](https://github.com/allegro/allegro-api/discussions) site, where other users can give their votes. Then we will be able to consult this topic and any possible change regarding labels with the appropriate team.

**Comment by t0is** [comment]
I opened a discussion, but it does not solve our problem. 

I do not believe we should be required to use anything like Allegro One, starting from 26th October, if the API is not ready for it. 

And putting such a requirement and forcing sellers to do more manual work, that is just ridiculous. 
I would like to ask you @Lukasz-Zurek to pass this information forward or to give me contact to someone I can discuss this with, because it is nonsense. 

Thanks.

**Comment by Lukasz-Zurek** [comment]
@t0is I will consult this case with specific department and will be back in this thread with some more details.

**Comment by t0is** [comment]
I am still waiting for info.

**Comment by Lukasz-Zurek** [comment]
@t0is I have already consulted it with a specific department. In our API, you can send Allegro One shipments without any restrictions. We provide Allegro One delivery methods in the API. Your problem seems to be related strictly to the labels. As I have already written - our API allows you only to download label(s) for only 1 order (apart from the order for a DPD multi-pack).

In the case of A4 label format, the label is located on 1/4 of the page and in the case of A6 it takes up the entire page.

You can set 4 labels on one page by yourself. Some integrations manage labels in this way on their own.

You can obtain more information about labels or specifically about Allegro Smart by contacting us via the [contact form](https://allegro.pl/pomoc/kontakt).
