### ISSUE TITLE
Category list with allowed condition type (such as new, used etc.)

### ISSUE THREAD

**Issue by dominikahr** [allegro/allegro-api#7738]
Hi all, 

can you please provide us with a list of all categories on Allegro with allowed conditions (such as new, used etc.). We saw that the condition selection is dependent on the category the product is in. This would help us set up bulk listings of products for those customers, who want to pick a different conditions than new.

Thank you in advance for your help! 

Best, 

Dominika

**Comment by Lukasz-Zurek** [comment]
I cannot provide that kind of list. But you can use [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2) to retrieve the lists of parameters that are supported by the category.id you indicated. 

You should remember about checking and updating the parameters on a daily basis, especially the dictionary type parameters, because their values may change in time.

You will find more information about the parameters in [our guide](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#offer-parameters).
