### ISSUE TITLE
REST API, unknown HTTP code 593

### ISSUE THREAD

**Issue by bologer** [allegro/allegro-api#7757]
We are currently using Allegro REST API and sometimes it produces HTTP code 593. 
It does not seem to be matching any of the existing HTTP codes nor standard.

Could you please explain in what cases it can happen?

**Comment by jezewskiBNetrox** [comment]
@bologer I believe it's HTTP code 503, because there is no existence of code 593 in the RFC specs. I never saw such either by years of using and maintaining integrations with Allegro. But generally sometimes errors >=500 happen. This is mostly random and it is independent of case until it is repeatable.

**Comment by PrzemyslawLukanowski** [comment]
Exactly, like @jezewskiBNetrox wrote - thank you for this answer. @bologer If you have a trace-id of these requests, you can send us some examples. We will check in on our side whether it was a temporary issue with one of our services or something else.

**Comment by bologer** [comment]
@jezewskiBNetrox @PrzemyslawLukanowski I see, thank you for the information.
