### ISSUE TITLE
Required parameter 

### ISSUE THREAD

**Issue by ZdenekMrazek** [allegro/allegro-api#7765]
Hi,
If I try to activate the offer for czech market, I am receiving this result:
 "Missing required parameters: 209870"

Based on the docs, if you omit the parameters, it will be filled by allegro itself based on item found. The internal Id of this product (EAN 8592131300903) in allegro is "da1e7ab2-003c-425b-959f-2e4a863ff65e".
I can´t get the reason for the error in the result. I probably need some explanation.

When I get the allegro product from the api, there is no parameter „Funkcje“ with id 209870. The question is, why it requires these parameters, when in default product it is not set? Couldn´t be there some invalid/missing data in the database for czech market?

Thanks.

Here is the request in JSON I am using to call to create the offer POST sale/product-offers
{
  "productSet": [
    {
      "product": {
        "id": "8592131300903",
        "idType": "GTIN"
      }
    }
  ],
  "stock": {
    "available": 97,
    "unit": "UNIT"
  },
  "delivery": {
    "shippingRates": {
      "name": "freeDelivery"
    },
    "handlingTime": "P3D"
  },
  "afterSalesServices": {
    "returnPolicy": {
      "name": "egenta_vratky"
    }
  },
  "sellingMode": {
    "format": "BUY_NOW",
    "price": {
      "amount": "999",
      "currency": "CZK"
    }
  },
  "external": {
    "id": "8592131300903"
  }
}

**Comment by PrzemyslawLukanowski** [comment]
Some products may have some missing required parameters because, for example, the parameter became required in the meantime. We provided a sample, of how to deal with those cases, in [our tutorial](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6):
<img width="622" alt="Zrzut ekranu 2023-10-13 o 14 22 57" src="https://github.com/allegro/allegro-api/assets/51473661/19465411-ba3a-4213-8ba5-d5907d0818e7">

The mentioned product is in category 67481, you can check the required parameters in this category by calling GET /sale/categories/67481/parameters (in the `"requiredForProduct"` field). If some of them are not included in the product data, you should provide them in the request as in the example above (in this particular case, it's only 209870).
