### ISSUE TITLE
Unable to find expense list for site cz order

### ISSUE THREAD

**Issue by VEVOR** [allegro/allegro-api#7884]
orderId:194642a0-772e-11ee-b742-c3a8742f2f18
GET /billing/billing-entries
response:
{
    "billingEntries": []
}

**Comment by VEVOR** [comment]
Shop backend screenshot
![7f7c5331127c074af2190983ea307b08](https://github.com/allegro/allegro-api/assets/99702013/76df42f5-0841-4390-89b7-47fd34cc7c94)

**Comment by Lukasz-Zurek** [comment]
It is correct, because you have registered your account on allegro-pl service so this is your base marketplace.

In the [/billing/billing-entries](https://developer.allegro.pl/documentation/#operation/getBillingEntries) resource, thanks to **"marketplaceId”** parameter, you can check the history of billing operations for the marketplace of your choice, e.g. allegro-cz.

If you do not use the parameter, we will return the base marketplace by default e.g. allegro-pl (like in your situation). So you cannot see the sales commission of the order for allegro-cz. You will have to use a "marketplaceId" filter.

You will find more information about it in [our tutorial](https://developer.allegro.pl/tutorials/listing-and-managing-offers-on-foreign-marketplaces-7GndGjeAATn#billing-operations).
