### ISSUE TITLE
Automatic Product Catalog Mapping

### ISSUE THREAD

**Issue by tlvrd** [allegro/allegro-api#7896]
Hello,

we are experiencing problems while trying to create products via your REST API.
We successfully uploaded the products with the EANs 4052025478544, 4052025478537, 4052025478520.
However when we try to upload another product with EAN 4052025478551, it is automatically mapped to the product with EAN 4052025478520 even though they are not the same product.
We do not understand this behaviour. Can you help us?

Best regards

**Comment by Lukasz-Zurek** [comment]
We will verify it closely, but please send me a trace-id of your request where we have returned a duplicate with a different EAN.

**Comment by ehonda** [comment]
Hi @Lukasz-Zurek, thanks for the fast response. I work with @tlvrd and will provide you with the `trace-id`, as they are currently unavailable. I just tried creating an offer (with product) for `EAN = 4052025478551` again, and we received the same result, the product-id `fa91d625-8580-4358-8137-097ba844e8cf` we received corresponds to the product with `EAN = 4052025478520`.

This was observed on the request with `trace-id = ec982e6dac556003`

**Comment by Lukasz-Zurek** [comment]
@ehonda We have assigned a product `fa91d625-8580-4358-8137-097ba844e8cf` because it has the same required, identifying parameters which you have provided for your offer. As I can see - the EAN: `4052025478520` corresponds for the same product as `4052025478551` but we don't have the second one in our product catalog and we could not create a duplicate because of the same parameters.

**Comment by ehonda** [comment]
Thanks for the clarification. However, I don't think I quite understand what's the issue though yet. I have collected the relevant data for this case, because I would like to make sure I understand why this product is mapped to a duplicate while others are mapped correctly.

For example, EAN `4052025478537` is correctly mapped to a different product, even though it is also closely related and almost similar to `4052025478520 / 4052025478551` in its parameters.

Here is a little investigation, concerning those EANs. Let's call give them more meaningful names to more easily differentiate between them:

* `hit: 4052025478520`
* `colliding: 4052025478551`
* `correct: 4052025478537`

# Existing product in allegro catalog `hit / 4052025478520 / fa91d625-8580-4358-8137-097ba844e8cf`

This is the the data we receive for the existing product parameters at `sale/product/fa91d625-8580-4358-8137-097ba844e8cf`:

```json
{
  "parameters": [
    {
      "id": "227353",
      "name": "Średnica",
      "valuesLabels": [
        "80,000 mm"
      ],
      "values": [
        "80.000"
      ],
      "unit": "mm",
      "options": {
        "identifiesProduct": true
      }
    },
    {
      "id": "17448",
      "name": "Waga produktu z opakowaniem jednostkowym",
      "valuesLabels": [
        "0,460 kg"
      ],
      "values": [
        "0.460"
      ],
      "unit": "kg",
      "options": {
        "identifiesProduct": false
      }
    },
    {
      "id": "225693",
      "name": "EAN (GTIN)",
      "valuesLabels": [
        "4052025478520"
      ],
      "values": [
        "4052025478520"
      ],
      "unit": null,
      "options": {
        "identifiesProduct": false,
        "isGTIN": true
      }
    },
    {
      "id": "129970",
      "name": "Marka",
      "valuesLabels": [
        "Relaxdays"
      ],
      "valuesIds": [
        "129970_619705"
      ],
      "values": null,
      "unit": null,
      "options": {
        "identifiesProduct": false
      }
    }
  ]
}
```

Here we can see that (at least among the existing product parameters) `Średnica` is the sole parameter that identifies the product.

# Parameters sent

These are the (product) parameters we send for the three products

## `hit / 4052025478520`

```json
{
  "parameters": [
    {
      "id": "17448",
      "values": [
        "0.460"
      ]
    },
    {
      "id": "227353",
      "values": [
        "80.000"
      ]
    },
    {
      "id": "225693",
      "values": [
        "4052025478520"
      ]
    },
    {
      "id": "129970",
      "valuesIds": [
        "129970_619705"
      ]
    }
  ]
}
```

We set the required parameters `Marka / 129970` and `Średnica / 227353` as well as the optional parameters `Waga produktu z opakowaniem jednostkowym / 17448` and `EAN (GTIN) / 225693`. The values we provide exactly match the existing values for `fa91d625-8580-4358-8137-097ba844e8cf`.

As expected, the product is correctly mapped.

## `colliding / 4052025478551`

```json
{
  "parameters": [
    {
      "id": "17448",
      "values": [
        "0.480"
      ]
    },
    {
      "id": "227353",
      "values": [
        "80.000"
      ]
    },
    {
      "id": "225693",
      "values": [
        "4052025478551"
      ]
    },
    {
      "id": "129970",
      "valuesIds": [
        "129970_619705"
      ]
    }
  ]
}
```

We provide the same value for the identifying parameter `Średnica` as with the `hit` product. Therefore, as you explained, it gets mapped to the same product in the catalog.

## `correct / 4052025478537`

```json
{
  "parameters": [
    {
      "id": "17448",
      "values": [
        "0.470"
      ]
    },
    {
      "id": "227353",
      "values": [
        "80.000"
      ]
    },
    {
      "id": "225693",
      "values": [
        "4052025478537"
      ]
    },
    {
      "id": "129970",
      "valuesIds": [
        "129970_619705"
      ]
    }
  ]
}
```

Here we also provide the same value for the identifying parameter `Średnica` as with the `hit` product. **In this case though, it gets mapped to a different product `baf7c5cf-6bca-4419-bcda-14c2e7e9a91e`**

# Open Questions

* Why does the mapping succeed for the `correct` product-offer, but not for the `colliding` product-offer?
* The three products all differ in color, is there a way we can make it so the identifying parameter is actually about their color (and not diameter)?

Thank you for your time!

**Comment by Lukasz-Zurek** [comment]
@ehonda Thank you for such a precise description. I have forwarded this case to another department. I will come back with a specific information.

**Comment by ehonda** [comment]
This thread is not stale, we're waiting for the results of the ongoing investigation.

**Comment by Lukasz-Zurek** [comment]
@ehonda I remember about your case. I have been consulting this case with another department. 

It is not easy to determine because in the process of creating a product, we always look for duplicates using various rules (so-called identification rules), where the set of parameters on the basis of which we are looking for differs depending on the category or e.g. brand, etc. Additionally, the main image of the product can also be taken for the process.

What is important - we allowed the product to be created 2 weeks ago but it does not mean that we would also allow it today because the rules on the basis of which we are searching - may change.

Obviously we have created products for 4052025478544, 4052025478537, 4052025478520, but our internal identification rules decided not to create a product for 4052025478551, it just decided to map to 4052025478551. 
Unfortunately I cannot give you one simple solution because our mechanism are specific and depends on various rules which are changing by the time.

What I can suggest is the fact that if you have such products which we have incorrectly assigned to your offers - please let me know. You can give a list of such products. We will verify them closely. We will try to correct the mechanism in such cases, if needed.

**Comment by ehonda** [comment]
@Lukasz-Zurek thanks for the insights and the detailed explanation!

Here are all such collisions we have observed on our uploads. In the tables, the row with a real `product_id` is the correctly mapped product, and the rows marked with `Collision` are the eans that are incorrectly mapped to the ean with the real `product_id`:

| product_id                           | ean           |
| ------------------------------------ | ------------- |
| fa91d625-8580-4358-8137-097ba844e8cf | 4052025478520 |
| Collision                            | 4052025478551 |
| Collision                            | 4052025478568 |

This is the example we discussed (`4052025478551` being mapped to `4052025478520 / fa91d625-8580-4358-8137-097ba844e8cf`). There is another ean, `4052025478568` which is also incorrectly mapped to `4052025478520 / fa91d625-8580-4358-8137-097ba844e8cf`

| product_id                           | ean           |
| ------------------------------------ | ------------- |
| 0e68b40a-3cc8-4ef3-a43d-b833667f7396 | 4052025213350 |
| Collision                            | 4052025478575 |

This is another such collision we observed. `4052025478575` is incorrectly mapped to `4052025213350 / 0e68b40a-3cc8-4ef3-a43d-b833667f7396`.

These are the only instances of collisions we have observed so far. If there are additional ones, I will let you know.

Thanks for your assistance! 👍

**Comment by Lukasz-Zurek** [comment]
@ehonda Thank you very much. I am forwarding this case to another department, for a verification process. As soon as I receive an answer, I will let you know in this thread. I will do my best to make it faster than last one.

**Comment by Lukasz-Zurek** [comment]
@ehonda First of all, let me explain our logic in these specific cases. Our product identification occurred after the Image + diameter rule. If we had a photo, we could set a similarity threshold appropriate for the category. 

We have already added an additional **Length** parameter to the category, if completed, it will also be taken into account for identification. Hopefully it will help you in that kind of situation.

I would like to ask you for a main images (one per Ean) which you have been sending in those requests. We will optimize the process.

**Comment by ehonda** [comment]
Hi @Lukasz-Zurek, sorry for the late response. What do you mean by main image? In our requests, we specify an array of images for the product, but we don't single one out to be the main image. Is it the first image in the array, perhaps?

**Comment by Lukasz-Zurek** [comment]
@ehonda No problem. Yes, it should be the first image in the array.

**Comment by ehonda** [comment]
Okay, these are the first / main images we put in the array for each of the eans on our uploads:

| ean           | main_image                                                                              |
| ------------- | --------------------------------------------------------------------------------------- |
| 4052025213350 | https://media.relaxdays.de/images/800/10021335_0_1_69e21505e8d53e7d4d6dc7ca70b6f182.jpg |
| 4052025478520 | https://media.relaxdays.de/images/800/10047852_0_1_5ddb2fd9d9e9557c7383d197a9ce5537.jpg |
| 4052025478551 | https://media.relaxdays.de/images/800/10047855_0_1_35754441790e77b4969a1859a904e18e.jpg |
| 4052025478568 | https://media.relaxdays.de/images/800/10047856_0_1_bad07c535b15f8b5facfc9ac126157a0.jpg |
| 4052025478575 | https://media.relaxdays.de/images/800/10047857_0_1_d20908595588d53b693f71e457e8a795.jpg |

**Comment by Lukasz-Zurek** [comment]
@ehonda We have already made some optimization in this process, so hopefully - you should not have similar situations in the future. If it happens, please let me know. We will be adjusting our identification conditions and rules on an ongoing basis.

**Comment by ehonda** [comment]
@Lukasz-Zurek thank you very much for the applied optimizations! We were now able to successfully upload eans `4052025478551` and `4052025478568` and they were correctly mapped to a separate product instead of colliding with `fa91d625-8580-4358-8137-097ba844e8cf / 4052025478520` 🎉 

The only product we still cannot map now is ean `4052025478575`, which still collides with `0e68b40a-3cc8-4ef3-a43d-b833667f7396 / 4052025213350`. The `trace-id` for the upload where we verified it still collides is `b8292b7ac76a6aca`.

**Comment by Lukasz-Zurek** [comment]
@ehonda Great :) Ok, now we are looking on the new case - thank you for the details.

**Comment by Lukasz-Zurek** [comment]
@ehonda We have verified it closely and it looks like the 4052025478575 and 4052025213350 are the same (have the same values of the parameters). I do not have a data with the image which you were trying to upload, but according to our basic logs, from our perspective it looked ok. Maybe you will be able to specify which EAN has a different color. We would be able to change it in our catalog.

**Comment by ehonda** [comment]
@Lukasz-Zurek thanks for coming back with additional information!

The main images for these eans are in fact different, but very subtly so:

| ean | main image |
| --- | --- |
| 4052025213350 | https://media.relaxdays.de/images/800/10021335_0_1_69e21505e8d53e7d4d6dc7ca70b6f182.jpg |
| 4052025478575 | https://media.relaxdays.de/images/800/10047857_0_1_d20908595588d53b693f71e457e8a795.jpg |

They look almost identical, but the first image has a caption "112" on the helmet, which the second doesn't. I would think that that is the main difference between the two products, so I suppose even specifying a color wouldn't help here, as they are the same color. The main difference should be in the EAN and the main image.

If differentiating the products by image / EAN doesn't work in this case, maybe a workaround would be to specify a slightly different color for one of the products. That could be something we can try, but it will be a while until we get to it, certainly not before the new year.

Anyway, thanks for the continuous and very helpful feedback on all these cases! It has been a very nice support experience so far 👍

**Comment by Lukasz-Zurek** [comment]
@ehonda Ok, no problem. I think that this is something that we can work on together 👌Our mechanism apparently takes color into main consideration. Thanks for your examples. I am forwarding this to another department, to consult this specific case. If I receive any additional information about the process, I will let you know.
