### ISSUE TITLE
Software statement ID

### ISSUE THREAD

**Issue by lukaszciszak** [allegro/allegro-api#7899]
Dzień dobry

Kilka dni temu wysłałem do Państwa prośbę o identyfikator Software statement ID (nr. zgłoszenia: 36927176).
Mogę prosić o informację na jakim etapie jest moja sprawa?

Pozdrawiam i życzę miłego dnia
Łukasz

**Comment by PrzemyslawLukanowski** [comment]
Dzień dobry,
Otrzymaliśmy już Twoją prośbę i przekazaliśmy odpowiedź. Wkrótce powinieneś ją otrzymać od opiekuna handlowego.

**Comment by lukaszciszak** [comment]
Dziękuje za szybką odpowiedź :)

Jestem w trakcie pisania modułu integrującego usługę "Wysyłam z Allegro" ze
sklepami internetowymi opartymi na Prestashop.
Moduł zostanie udostępniony do sprzedaży. Po wykupieniu licencji
właściciele sklepów otrzymają kopię tego modułu.
Wersja modułu, nad którą pracuje jest przeznaczona dla sklepów, które
używają innego modułu do integracji z Allegro, który korzysta z autoryzacji
Device.

Wersję testową modułu, która używa autoryzacji Dynamic Client Registration
mam gotową i chciałbym przekazać ją pierwszej osobie, która zacznie z niej
korzystać.
Stąd moja prośba o udostępnienie identyfikatora Software statement ID.
Będę bardzo wdzięczny za szybkie załatwienie sprawy.

Pozdrawiam i życzę miłego dnia
Łukasz

czw., 2 lis 2023 o 11:42 PrzemyslawLukanowski ***@***.***>
napisał(a):

**Comment by PrzemyslawLukanowski** [comment]
Dziękuję, udzielimy dalszych instrukcji poprzez opiekuna handlowego.

**Comment by zhangliangce** [comment]
Hello!
I want to registry a application to join the Allegro day.So I need a software_statement_id  for my application.Please help me!
Regards!

niobrand57@hotmail.com

**Comment by PrzemyslawLukanowski** [comment]
@zhangliangce You can register the application on https://apps.developer.allegro.pl/. Software statement ID can be given only in particular cases, which we describe in [our tutorial ](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#dynamic-client-registration). If [code](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#authorization-code-flow) or [device](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#device-flow) flow is not sufficient for you, contact us via the [contact form](https://allegro.pl/pomoc/kontakt) and justify why you need to use DCR type of authorization instead of code or device.

**Comment by zhangliangce** [comment]
Hello!I have linked my app to allegro account.But I get only access_token no refresh_token when I was getting token.It is unuseful because it change every second any request.How to get refresh_token?

**Comment by PrzemyslawLukanowski** [comment]
Hello, I answered in the #7068 thread.

**Comment by zhangliangce** [comment]
ok
