### ISSUE TITLE
Creation of a new product card

### ISSUE THREAD

**Issue by dominikahr** [allegro/allegro-api#7925]
Hi there, 

I wanted to ask you if you could please specify the rules for a creation of a new product card. 

Is it possible to create a new product card even though the product with the same EAN already exists on Allegro? Or are there only these two options: 

- connect offer to already existing product card, so in this case we should only send currency, condition, gtin, price, stock
- create a new product card and assign the offer to it (in this case are the required parameters for the product category have to be sent as well) 

Thank you in advance for your help! 

All the best, 

Dominika

**Comment by Lukasz-Zurek** [comment]
Yes, using [POST /sale/product-offers](https://developer.allegro.pl/documentation/#operation/createProductOffers) you can list with one request an active offer assigned to a product:

-  which already exists in our Catalog - you can use product data via [GET /sale/products] (https://developer.allegro.pl/documentation/#operation/getSaleProducts),
- which is not in our Catalog - then we will automatically create it.

Please read our [tutorial](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#how-to-list-an-offer-with-a-product).

**Comment by dominikahr** [comment]
But I can I assign an offer to a product, which already is included in the catalog, but create a new product card for it? So in the end there will be 2 products with the same EAN in the catalog? It happened to me many times that I found more product cards for the same EAN, for example: 
![obrazek](https://github.com/allegro/allegro-api/assets/147524238/43c35026-dd72-45ed-97d3-b4e9e6e285bb)
![obrazek](https://github.com/allegro/allegro-api/assets/147524238/bc7f578b-efd7-4508-8a08-39abf9b071c9)

Especially in those cases, when there is something wrong with the existing product card and instead of suggesting changes we would like to create a new product card.

**Comment by Lukasz-Zurek** [comment]
No, it won't be possible. If you try to create a similar product because we should return an error about a duplicate which already exists in our product catalog. If you try to list an offer, providing similar data - we will find a product (if it exists) from our catalog and will assign to the offer, so there is nothing you can do about it. It is automatic process.

The product which you have mentioned - has a different brand, maybe this is why it has been created succesfully. It could be verified someday and we could delete an incorrect duplicate. But it is not up to our team.
