### ISSUE TITLE
Expired Token

### ISSUE THREAD

**Issue by DHSC1** [allegro/allegro-api#8241]
Hello,
we are encountering a problem where orders and other information are not being updated via API. We have discovered that the issue is due to an expired API token. This issue is on seller RadanSportCZ. We have some other accounts where tokens are being refresh properly. In the account on the allegro portal, the account does not appear to be blocked. However, I managed to navigate to the "My assortment" section, where suddenly 0% appeared in the partner integration process.
![image](https://github.com/allegro/allegro-api/assets/144317759/5f03ab02-ccdf-431b-a940-7f65ca325ca3)

I should mention that the account went through all the verification and offers was standardly being sold from the account. We contacted support, where we received information that everything was verified:
Ticket [ ref:!00D240aE05.!500Ti03UiGS:ref ]:
"Your bank account is verified.
This verification was opened from your account on 2.11.2023, no further bank account verification is needed from Allegro, if you want to close this verification leave it unresponsive and it will automatically close itself."

So we don't know which way to go. With the next question about expired api keys, your support will automatically redirect us to github (because the email will contain the word/shortcut API).

Thank you in advance

**Comment by PrzemyslawLukanowski** [comment]
Hello, I have checked our logs, but when it comes to the last two weeks, it seems that the user has not used any external application - there isn't any trace of the 401 Unauthorized status code. The same applies to the refresh token - there is no trace for valid or invalid operation. Maybe you have some logs on your side associated with the failed refresh token operation? If so, please attach them to your ticket, and let the support team know that it should be forwarded to the API Support Team and it refers to the #8241 ticket on GitHub.

Currently, the user should re-authorize your application to generate a new valid pair of tokens. There could be several reasons why the token refresh failed, for example - tokens lost validity due to changes on the account (password or e-mail) or there were some network connection issues because of which you didn't save newly generated tokens on your side.
