### ISSUE TITLE
I dont understand required parameters for offers

### ISSUE THREAD

**Issue by manweCZ** [allegro/allegro-api#8344]
Hello,
I've been trying to publish our client's products on Allegro.cz.
For simplicity sake, we're only publishing products that are already present on Allegro (I check if product EAN already exists on Allegro before trying to publish it).

However, for some (seemingly random) products, there will be an error like this: (im trying to publish an offer for product with EAN 4003198102033, which should already be present on Allegro).

Ive published around 50 products so far, most of them are in the same category on Allegro (category ID: 64508). 

```
An error has occurred: stdClass Object
(
    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [code] => ConstraintViolationException.MissingRequiredParameters
                    [message] => Missing required parameters: 235129
                    [details] => ConstraintViolationException.MissingRequiredParameters
                    [path] => parameters
                    [userMessage] => Uzupełnij parametry obowiązkowe: Rodzaj.
                )
        )
)
```

What I absolutely dont understand is the randomness of required parameters. I thought parameters can be required by certain product category. However I've already published around 50 products in the same category 64508 without needing to supply the Parameter 235129.
Also - some parameters (still within the same category) seem to be required in the product description, and others in offer description.

Is there a way to _get required parameters for certain offer_? So far it seems very random and I am very confused because there seem to be no cohesive information what I should supply to any given offer, as sometimes I need to supply no parameters at all, sometimes I need to supply parameter (like 212158 for product definition, or 248489 for offer parameters), while other products pass without needing any parameters at all, all within the same category 64508.

Could somebody lead me to an answer?
Thank you.

The data I am sending for this particular example are these: https://i.imgur.com/9viVS11.png

**Comment by MaciejFrackowiak** [comment]
First, you should check which parameters are required in the selected category. So, please call [GET /sale/categories/{categoryId}/parameters](https://developer.allegro.pl/documentation/#operation/getFlatParametersUsingGET_2) to check it. 
For the category with id=64508, the parameter "Kind" (id=235129) is required. Also, it has another mask - "describesProduct": true - which means, that this parameter describes the product, so it should be included under the [product.Set](https://developer.allegro.pl/documentation/#operation/createProductOffers) part of the request.
Then, you can check existing products from our product base - just call [GET /sale/products](https://developer.allegro.pl/documentation/#operation/getSaleProducts) with GTIN as a parameter. 
You will receive a list of products - with the provided EAN there is only one product - so check its parameters.
You will find that the product does not have a "Kind" parameter in its structure. It means that you should add the parameter "Kind" to your request when you try to list a new offer because the "Kind" parameter is required as you checked it before.
After that, you offer will be listed - all the necessary parameters will be assigned to the product with EAN=4003198102033.

**Comment by manweCZ** [comment]
@MaciejFrackowiak 
Thank you for you answer.

So there are products already listed on Allegro that might have some required parameters missing and I have to fill them before publishing an offer?

Thank you.

**Comment by manweCZ** [comment]
@MaciejFrackowiak 
ok thank you, managed to sort it out.
I have (hopefully) last question.

Let's say I publish an offer with 10 stock quantity. Client sells the products with other means, and the stock quantity changes.

1) if the quantity is still > 0 I just update the offer with the correct quantity
2) if the quantity is 0, I need to unpublish the offer, is that correct? as I cant call stock => available  with 0 quantity, right?

thank you

**Comment by MaciejFrackowiak** [comment]
1. Yes.
2. With stock=0 offer will finish automatically.

**Comment by manweCZ** [comment]
ad 2) if i then update offer with stock > 0 it will republish automatically?

**Comment by MaciejFrackowiak** [comment]
No, you have to send a new request with publication.status=ACTIVE.

**Comment by manweCZ** [comment]
@MaciejFrackowiak ok thank you :)

**Comment by manweCZ** [comment]
@MaciejFrackowiak 

one more question - im importing orders to client's CRM - I fetch orders with status READY_FOR_PROCESSING - such orders should either be already paid (if the payment is online) or should await payment if they are Cash on Delivery, am I correct?

Thank you

**Comment by MaciejFrackowiak** [comment]
READY_FOR_PROCESSING is a status for both types of orders:
- paid by bank account/card
- COD orders

**Comment by manweCZ** [comment]
ok great, thank you
