### ISSUE TITLE
the offer is not matched to the product in the portal

### ISSUE THREAD

**Issue by saleschristina** [allegro/allegro-api#8396]
Hello, 
 I did auction from Baselinker to Allegro and the offers is not connected with the product in the portal. 
I wrote to allegro and they think that there is some problem with API maybe. The account is CHRISTINA_profi.

Thank you for help.
Karolína Casková
CHRISTINA kosmetika

**Comment by MartaNowaczyk** [comment]
Hello, in such cases we need specific data (mainly technical data) to be able to verify it. If something doesn't work and you use integration, your first contact should be the support of the application you are using, i.e. Baselinker.
However, I managed to find the offer with the problem, because only one of them shows an error. You have not completed the required "Type" parameter for this offer, therefore the product cannot be added. The exact message: "Nelze vytvořit product without any special requirements, not to mention the following parameters: [Type]". You should complete this parameter.
