### ISSUE TITLE
can you please activate my sandbox acc: 106896401

### ISSUE THREAD

**Issue by JanJasa** [allegro/allegro-api#8464]

**Comment by PrzemyslawLukanowski** [comment]
I've activated your account. You've chosen a regular account, so keep in mind that if you want to list or manage offers via API you'll need a company account - you can transform the current account or create a new one.

**Comment by PrzemyslawLukanowski** [comment]
We can activate only Sandbox accounts. When it comes to the production, please [follow the instructions](https://allegro.pl/pomoc/dla-kupujacych/aktywacja-konta/czym-jest-pelna-aktywacja-konta-i-jak-moge-ja-przeprowadzic-GDeq5WOB8uE). If you have any questions, use [contact form](https://allegro.pl/pomoc/kontakt).

**Comment by JanJasa** [comment]
I need to use the API for importing products and downloading orders from Allegro. However, I'm having trouble with authorization and product import: https://allegro.pl.allegrosandbox.pl/auth/oauth/token?grant_type=client_credentials correctly returns a token, but then it can't be used in https://sandbox.allegroapi.io/sale/product-proposals. This function doesn't return anything, not even an error message. Do you have any idea where can be ploblem? I try to figure it out couple of days.

**Comment by PrzemyslawLukanowski** [comment]
Client credentials type of authorization gives you access to resources marked as bearer-token-for-application in our documentation (without user context). To use all the other ones, marked as bearer-token-for-user, generate a token with [code](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#authorization-code-flow) or [device](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#device-flow) type of authorization.

**Comment by JanJasa** [comment]
Thank you, I have also tried this procedure, but after generating the [link](https://allegro.pl.allegrosandbox.pl/auth/oauth/authorize?response_type=code&client_id=802a4794b05240e1af22d9a8f6d5361c&redirect_uri=https%3A%2F%2Fmaster.hightechdevelopment.group%2Fphp-api%2Falegro-product.php) the target page displays "Nie możemy wyświetlić strony Numer błędu: 591e7d205fe611c2", and I am completely stuck, unable to proceed...

**Comment by PrzemyslawLukanowski** [comment]
That's because you registered a device type of application:
<img width="601" alt="Zrzut ekranu 2024-02-14 o 09 48 18" src="https://github.com/allegro/allegro-api/assets/51473661/d96a782a-f97a-413d-b68d-2ed08e59a325">

 but you are trying to generate a token using [authorization code](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#authorization-code-flow) flow instead of a [device](https://developer.allegro.pl/tutorials/authentication-and-authorization-m09BlVyo7iY#device-flow) flow.

If you want to use code flow, register the application using the first option:

<img width="629" alt="Zrzut ekranu 2024-02-14 o 09 51 19" src="https://github.com/allegro/allegro-api/assets/51473661/0ac9bb9f-4054-4e98-b528-d77c55c04783">
