### ISSUE TITLE
Retrieving product signature

### ISSUE THREAD

**Issue by studiowizjo** [allegro/allegro-api#8705]
How can I fetch the "Signature" field value for a product (offer)? I've tried using methods from: https://developer.allegro.pl/documentation#operation/getOrdersDetailsUsingGET and https://developer.allegro.pl/documentation#operation/getSaleProduct, but neither returns this information.

For example, I have an offer with the ID: 14716709296, and the "Signature" field contains the value "XT2169 Чер СР Incell №1". Unfortunately, none of the methods mentioned above return this information.

However, it is visible when editing the offer: https://allegro.pl/offer/14716709296

![Zrzut ekranu 2024-03-22 102651](https://github.com/allegro/allegro-api/assets/3818874/778741e1-0267-4b49-99da-2b6cd555ec9a)

and on the offer list: https://allegro.pl/moje-allegro/sprzedaz/obsluga-ofert/moj-asortyment. 

![Zrzut ekranu 2024-03-22 102217](https://github.com/allegro/allegro-api/assets/3818874/3f136cb3-ddfc-4635-9b7c-b15713509e63)

**Comment by Lukasz-Zurek** [comment]
We return this in **external.id** field when you use:

- **GET /sale/product-offers/14716709296** (offer's details) - I have checked some logs and we return it correctly,
- [GET /order/checkout-forms](https://developer.allegro.pl/documentation#operation/getListOfOrdersUsingGET) (orders list),
- [GET /order/checkout-forms/{id}](https://developer.allegro.pl/documentation#operation/getOrdersDetailsUsingGET) (order's details.

We will not return this data in [GET /sale/products/{productId}](https://developer.allegro.pl/documentation#operation/getSaleProduct), because using this resource you can only check product's data. The signature (**external.id**) can be added to the offer.
