### ISSUE TITLE
get createOffer result status still in 202

### ISSUE THREAD

**Issue by yu-www** [allegro/allegro-api#8966]
Hi there,

after I call the https://api.allegro.pl.allegrosandbox.pl/sale/product-offers api in sandbox,I got the response status is 202,and I call the 
https://api.allegro.pl.allegrosandbox.pl/sale/product-offers/7759809797/operations/4ac88960-e7c1-4207-8948-68884f9afade form the header location,

request={"offer":{"id":"7759809797"},"operation":{"id":"4ac88960-e7c1-4207-8948-68884f9afade","status":"IN_PROGRESS","startedAt":"2024-04-28T06:13:25.289Z"}} 

Half an hour later，It's still in IN_PROGRESS status.

Why has this offer been IN_PROGRESS status for so long?

**Comment by Lukasz-Zurek** [comment]
It is a correct behavior. It can took up to two hours. Please read more about this process in our previous [news](https://developer.allegro.pl/news/we-will-verify-offers-more-precisely-and-extend-the-publication-time-v8dEqvD5xTg).

**Comment by Lukasz-Zurek** [comment]
I would also like to add that **202 Accepted** means that we will perform the task asynchronously due to the longer duration of the operation. You can read more about it [here](https://developer.allegro.pl/tutorials/list-offer-assigned-product-one-request-D7Kj9M71Bu6#integration-with-an-asynchronous-api).
