### ISSUE TITLE
Offer management

### ISSUE THREAD

**Issue by Liritt** [allegro/allegro-api#9243]
Hello,

I have a question as to whether or not we can avoid offer duplication in our situation : 
- In our system, when we create an offer on Allegro we stock it, with its offer ID.
- If we have an update to do, we use the stocked offer ID and update the offer

The problem lies in the deactivation of an offer. 
In our system, we delete the offer that contains the offer ID from Allegro from our database. It could be because we have no stock anymore for example. 
Thanks to this deletion our system detect that we have to do the same on the marketplace and attempt the deactivation of our offer on Allegro.
Now, let's imagine that we have stock again. We recreate the offer in our system, but we do not have the offer id from Allegro anymore. Because of this, we have to duplicate the offer instead of just reactivate the already existing offer associated for the same product.
We also saw that putting an offer for a product where we previously deactivated an offer allowed the customer to see the expired offer on the front.
![image](https://github.com/allegro/allegro-api/assets/110486250/e1030644-13a3-4629-b3db-34a2d3b04258)

Knowing that our system behavior cannot be changed, does Allegro propose a way to resolve this situation and how can we hide the expired offer(s) from the front ? (if it is possible)

Thanks in advance

**Comment by AureliuszBrussy** [comment]
I can't think of any solution if you can't change the behavior of your system (so that the offer or product on your side is not completely removed). 

The model from our perspective is that the product should not be deleted, and once the stock is supplemented, the offer should be reactivated, unless it has already been archived on our side. 

You can't delete the viewing of a ended offer, but don't worry - it is not exposed when buyers search for the product on our site.
