### ISSUE TITLE
Shipment creation in sandbox returning "delivery method not found"

### ISSUE THREAD

**Issue by Liritt** [allegro/allegro-api#9302]
Występuje problem: 
 - [ ] z zasobem REST API / with a REST API resource
 - [ ] ze środowiskiem produkcyjnym / with the production environment
 - [X] ze środowiskiem testowym / with the test environment
 - [ ] z logowaniem lub autoryzacją / with login or authorization
 - [ ] na portalu https://developer.allegro.pl/ / at https://developer.allegro.pl/en/
 - [ ] inny / other

:beetle: **Opis / Description**

Hello, 

I was trying to create a shipment for a test order and, as written in the documentation, I took the delivery method id that was chosen by the customer in the order payload delivery.method.id, but the shipment creation was rejected because the DELIVERY_METHOD_NOT_FOUND, "Requested delivery method was not found". 
As I took what was returned from the order, how can it not be found ?

trace-id of a request : 2f6a1097be3a060e
order id : 88067690-3242-11ef-a9ef-597d39768739
sandbox account name : spacefoot_test
endpoint used : POST shipment-management/shipments/create-commands

Could you please check it ?

Thanks in advance

**Comment by PrzemyslawLukanowski** [comment]
Hello, the "Courier delivery" delivery method is not associated with any specific carrier and cannot be shipped via Ship With Allegro. You can create parcels only for delivery method IDs that are returned in the [GET /shipment-management/delivery-services](https://developer.allegro.pl/tutorials/how-to-manage-parcels-via-ship-with-allegro-ZM9YAyGKWTV#how-to-retrieve-a-list-of-delivery-services).

**Comment by Liritt** [comment]
Then why the documentation says that it must be the delivery method chosen by the buyer in the order ? If we have to choose it ourselves.
![image](https://github.com/allegro/allegro-api/assets/110486250/5b63d5b5-36d4-4703-8408-8c4e241f83df)

**Comment by PrzemyslawLukanowski** [comment]
That's true, but not all of the delivery methods are supported by the Ship With Allegro Service - such orders, with "Courier Delivery" cannot be handled by this service. That's why the first endpoint described in the documentation and [tutorial](https://developer.allegro.pl/tutorials/how-to-manage-parcels-via-ship-with-allegro-ZM9YAyGKWTV#how-to-retrieve-a-list-of-delivery-services) is [GET /shipment-management/delivery-services](https://developer.allegro.pl/documentation/#operation/getDeliveryServices):

<img width="524" alt="Zrzut ekranu 2024-06-28 o 09 10 43" src="https://github.com/allegro/allegro-api/assets/51473661/7dea6016-13fa-44c3-9ffd-d40c77d0603b">

You don't need to choose it yourselves, cause it will be the same delivery service as the delivery method chosen by the buyer, but the problem is with the "Courier Delivery", which is not supported by the Ship With Allegro service.

**Comment by Liritt** [comment]
So for all delivery methods it's ok but only this one isn't good ? Which means that for the rest we can put what was chosen by the buyer, and for this one we put one of our choice right ?

**Comment by PrzemyslawLukanowski** [comment]
Not only this one, there are some other delivery methods that are not handled by Ship With Allegro, for example: Fedex or GLS.

**Comment by PrzemyslawLukanowski** [comment]
And no, you cannot for this one put one of your choice, such delivery method cannot be handled by Ship With Allegro.

**Comment by Liritt** [comment]
I tried to, but I still don't understand which value to put in this field. I tried to put at least 10 different ids among those returned with endpoint shipment-management/delivery-services but for every single one of them I got the error DELIVERY_METHOD_NOT_AVAILABLE, Delivery Method is not available for this order... How do we know which value to put for an order ?

**Comment by PrzemyslawLukanowski** [comment]
As I mentioned, this delivery method is not supported by the Ship With Allegro, so you cannot choose any value. It is not possible to ship such orders with shipment-management endpoints. A list of available delivery services, that can be handled by Ship With Allegro is returned in the [GET /shipment-management/delivery-service](https://developer.allegro.pl/documentation/#operation/getDeliveryServices). Delivery methods that are not returned here cannot be handled by POST shipment-management/shipments/create-commands.

**Comment by Liritt** [comment]
Yes, and what I said above is that I tried using different values returned from this endpoint and that is always returned me the error DELIVERY_METHOD_NOT_AVAILABLE and this is why I do not understand which value I am supposed to put. For example for this call : 1ba600d11ad52ba

**Comment by PrzemyslawLukanowski** [comment]
You cannot create a parcel for this order via shipment-management endpoint, because the delivery method, from the order, is not supported by Ship With Allegro. For example, if in your order there is "A" delivery method, then you must use "A" delivery method from shipment-management/delivery-services. 
Some delivery methods are not supported by Ship With Allegro, for example - the "D" delivery method, like Courier delivery/Fedex. You have such order, with the "D" delivery method, but the /shipment-management/delivery-services returns you only "A", "B" and "C". So it means you cannot create a parcel for this order via Ship With Allegro, there's no delivery service on which you can ship such parcel.

So the answer to 

> why I do not understand which value I am supposed to put

is there is no correct value for this order delivery method, it cannot be handled by the shipment-management endpoint

**Comment by Liritt** [comment]
Ok so in this case I finally understand ! That means that I should just skip the shipment creation and directly add tracking numbers and update order status to "sent" right ?

**Comment by Liritt** [comment]
Which means that the order management workflow would just be : 
- add invoice to order
- add tracking number
- put order status to sent
right ?

**Comment by PrzemyslawLukanowski** [comment]
Yes, exactly :)

**Comment by Liritt** [comment]
Ok, thanks a lot for your time :)
